openlayers/README.md
openlayers/build.boot
openlayers/resources/deps.cljs

@olivergeorge @jeluard Please let me know if you think the README could be improved somehow.

OpenLayers as native Closure library

---

leaflet/README.md
leaflet/build.boot
leaflet/resources/cljsjs/common/leaflet.ext.js

add Leaflet

---

openlayers/README.md
openlayers/build.boot

Also fixes issue with missing ol.ext.rbush

Update to new release of openlayers (v3.2.0)

---

react-with-addons/resources/cljsjs/common/react.ext.js

added missing TransitionGroup extern to react-with-addons

---

chance/README.md

forgot to do this in the original PR...

add README for chance

---

jsdiff/README.md
jsdiff/build.boot
jsdiff/resources/cljsjs/common/jsdiff.ext.js

https://github.com/kpdecker/jsdiff

add jsdiff library

---

jquery-ui/README.md
jquery-ui/build.boot
jquery-ui/resources/cljsjs/common/jquery-ui.ext.js

one small cheat: download task was getting a 403 error from jqueryui download site. I DL'ed the zip and put it up on github in a repo i created for that purpose

jquery-ui 1.11.3 support

---

react-router/README.md
react-router/build.boot
react-router/resources/cljsjs/common/react-router.ext.js

follow up to
https://github.com/cljsjs/packages/issues/46
thanks @pandeiro for doing pretty much all the work :)

add react-router package

---

flot/README.md
flot/build.boot
flot/resources/cljsjs/common/flot.ext.js
flot/resources/cljsjs/common/flot.plugins.crosshair.ext.js
flot/resources/cljsjs/common/flot.plugins.selection.ext.js
flot/resources/cljsjs/common/flot.plugins.time.ext.js

squashed the commits from #55 (example is removed)

add flot library

---

d3/README.md
d3/build.boot
dimple/README.md
dimple/build.boot
dimple/resources/cljsjs/dimple/common/dimple.ext.js

Add dimple package (issue #58)
Also fixes d3 - not sure if this needs to be a separate PR?

Add dimple package

---

react/resources/cljsjs/common/react.ext.js

Addresses #64 and covers SyntheticEvent externs ( https://github.com/swannodette/react-cljs/issues/11)

SyntheticEvent externs and a typo

---

pako/README.md
pako/build.boot
pako/resources/cljsjs/pako/common/pako.ext.js

see: https://github.com/nodeca/pako

new package pako 0.2.5 - zlib port to javascript.

---

d3/resources/cljsjs/d3/common/d3.ext.js

Add:
- d3.selection.exit()
Remove:
- d3.enter

Improve d3 externs

---

stripe/README.md
stripe/build.boot
stripe/resources/cljsjs/common/stripe.ext.js
stripe/resources/deps.cljs

new pull request. I couldn't figure out how to properly rebase so i just killed my repo, re-forked and committed the changes

stripe vendor lib

---

document-register-element/README.md
document-register-element/build.boot

Introduced the cljsjs package for [document-register-element](https://github.com/WebReflection/document-register-element).

[document-register-element] Added 0.2.1

---

markdown/README.md
markdown/build.boot
markdown/resources/cljsjs/common/markdown.ext.js

Replaces https://github.com/cljsjs/packages/pull/117

Add markdown-js package

---

fixed-data-table/README.md
fixed-data-table/build.boot

New Fixed Data Table release with proper support of custom cellRenderer on React 0.13

[fixed-data-table] 0.2.0

---

openlayers/build.boot

Updated to latest 3.5.0-0 version of Openlayers.

Openlayers 3.5.0-0

---

fastclick/README.md
fastclick/build.boot
fastclick/resources/cljsjs/fastclick/common/fastclick.ext.js

Adds a package for fastclick.
https://github.com/ftlabs/fastclick
Thanks!

[fastclick] Add fastclick.

---

fixed-data-table/README.md
fixed-data-table/build.boot

Upped to latest version of fixed-data-table and included additional split css files

[fixed-data-table] release 0.4.1-0

---

moment-range/README.md
moment-range/build.boot
moment-range/resources/cljsjs/common/moment-range.ext.js

Hello,
I've added moment-range 
https://github.com/gf3/moment-range
http://gf3.github.io/moment-range/
It is a plugin extension for the already existing moment(js) library.
Thanks for considering! Let me know if I've forgotten to do anything...

Added moment-range.js - Range extenstion for momentjs

---

d3/README.md
d3/build.boot
d3/resources/cljsjs/d3/common/d3.ext.js

Bump the package release number to make this ready for release.

Add missing externs for innerTickSize() and outerTickSize().

---

dygraphs/README.md
dygraphs/build.boot
dygraphs/resources/cljsjs/dygraph/common/dygraph.ext.js

Adds the current version of the canvas based line charting library Dygraph (http://dygraphs.com)

[dygraph] Create package

---

bytebuffer/README.md
bytebuffer/build.boot
bytebuffer/resources/cljsjs/bytebuffer/common/bytebuffer.ext.js
long/README.md
long/build.boot
long/resources/cljsjs/long/common/long.ext.js

This PR adds the long and bytebuffer modules from dcode.io.
* https://github.com/dcodeIO/long.js
* https://github.com/dcodeIO/bytebuffer.js

Add long and bytebuffer

---

vis/build.boot
vis/resources/cljsjs/vis/common/vis.ext.js

I've added missing externs using [javascript-externs-generator](https://github.com/jmmk/javascript-externs-generator) which generated more complete externs.

[vis] Added missing externs

---

openlayers/README.md
openlayers/build.boot

Bumping Openlayers to the most recent version.

Bumped Openlayers version to 3.10.1.

---

jqconsole/README.md
jqconsole/build.boot

There has been a bug fix, bumping.

Bump jq-console to 2.13.2

---

react-quill/README.md
react-quill/boot.properties
react-quill/build.boot
react-quill/resources/cljsjs/react-quill/common/react-quill.ext.js

I couldn't really confirm whether this works but it looks a lot like reactabular, so I suspect the error on my side somewhere else.
I'd appreciate it if someone could have a look. Thanks!

Package react-quill 0.3.0

---

react-grid-layout/README.md
react-grid-layout/build.boot
react-grid-layout/resources/cljsjs/react-grid-layout/common/react-grid-layout.ext.js

[react-grid-layout] 0.8.5-0

---

pouchdb/README.md
pouchdb/build.boot
pouchdb/resources/cljsjs/pouchdb/common/pouchdb.ext.js

This just bumps the version.
I haven't been following cljsjs for a while. Have things changed significantly?

[pouchdb] 5.1.0

---

spin/README.md

Loving the package, thanks for providing it! I think the title may have been left over from some template.

Fix title naming

---

d3geo/README.md
d3geo/build.boot
d3geo/resources/cljsjs/d3geo/common/d3geo.ext.js

lets you use the extended D3 projections from CLJSJS.

add a d3geo package

---

rrule/README.md
rrule/build.boot
rrule/resources/cljsjs/rrule/common/rrule.ext.js

https://github.com/jkbrzt/rrule

RRule 2.1.0

---

fixed-data-table/build.boot

fixed-data-table to version 0.6.0

---

opentype/README.md
opentype/build.boot
opentype/resources/cljsjs/opentype/common/opentype.ext.js

cljsjs package for [opentype js](http://opentype.js.org/)

cljsjs package for opentype

---

labella/README.md
labella/build.boot
labella/resources/cljsjs/labella/common/labella.ext.js

cljsjs package for [labella](http://twitter.github.io/labella.js/)

cljsjs for labella.js

---

autobahnjs/README.md
autobahnjs/build.boot
autobahnjs/resources/cljsjs/autobahnjs/common/autobahn.ext.js

I created a package for Autobahn|JS, a WAMP Client Library. Locally tested. Installed it with `boot package pom jar install`

Adds Autobahn|JS 0.9.9  as package

---

highcharts/README.md
highcharts/build.boot

Add explicit jQuery dependency to Highcharts

---

jquery-daterange-picker/build.boot
jquery-daterange-picker/resources/cljsjs/common/jquery-daterange-picker.inc.css
jquery-daterange-picker/resources/cljsjs/development/jquery-daterange-picker.inc.js

Version 0.0.9 includes bug fixes and enhancements
Also updated moment and jQuery version
Some of the bug fixes:
- Auto close
- Range highlighter
https://github.com/longbill/jquery-date-range-picker/releases

[jquery-daterange-picker] Update version

---

blockapps/README.md
blockapps/build.boot
blockapps/resources/cljsjs/blockapps/common/blockapps.ext.js

https://github.com/blockapps/blockapps-js

[blockapps] adds blockapps 2.2.5

---

d3kit/README.md
d3kit/build.boot
d3kit/resources/cljsjs/d3kit/common/d3kit.ext.js

package for [d3kit](https://github.com/twitter/d3kit), a tool for simplifying work with d3js

cljsjs package for d3kit

---

moment/resources/cljsjs/common/moment.ext.js

Adds missing isBetween method into externs

isBetween into externs

---

waypoints/README.md
waypoints/build.boot
waypoints/resources/cljsjs/waypoints/common/waypoints.ext.js

Upgrade waypoints library to 4.0.0.  Also generated a slightly more complete externs file using http://jmmk.github.io/javascript-externs-generator/

Waypoints 4.0

---

openlayers/README.md
openlayers/build.boot

I simply changed the version numbers and checksums. Tried locally with figwheel and :advanced build, both seemed to work fine.

Upgrade ol3 to latest version

---

material/build.boot

I've updated Material to the latest version from upstream, and tested it locally.

[Material] updated to v1.1.0

---

react-mdl/README.md
react-mdl/build.boot
react-mdl/resources/cljsjs/react-mdl/common/react-mdl.ext.js

https://github.com/tleunen/react-mdl

[react-mdl] add react-mdl library

---

d3-cloud/README.md
d3-cloud/build.boot
d3-cloud/resources/cljsjs/d3-cloud/common/d3-cloud.ext.js

This is my first attempt to create a package, it works for me locally, the package task is a little goofy so feel free to refactor it

add d3-cloud package

---

forge/build.boot
forge/resources/cljsjs/forge/common/forge.ext.js

Fixed silly mispaste in forge

---

exif/README.md
exif/build.boot
exif/resources/cljsjs/exif/common/exif.ext.js

This is my first pull request to cljsjs, so if I missed anything or if I can change anything to be more helpful, please let me know. 
Tested in simple and advanced compilation. Here's an example of a widget using this library: http://www.upgradingdave.com/blog/html/exif.html
Thanks, 
Dave

[exif] add exif.js library

---

moment/build.boot
moment/resources/cljsjs/common/moment.ext.js

Added extern for this function:
http://momentjs.com/docs/#/customization/relative-time-threshold/

[moment] Add moment.relativeTimeThreshold extern

---

react-bootstrap/build.boot
react-bootstrap/resources/cljsjs/react-bootstrap/common/react-bootstrap.ext.js

Just includes some components that were not in the externs file

[react-bootstrap] Add missing navbar externs

---

syn/README.md
syn/build.boot
syn/resources/cljsjs/syn/common/syn.ext.js

Adds [syn](http://github.com/bitovi/syn) - Standalone Synthetic Event Library

[syn] Add syn

---

sizzle/README.md
sizzle/build.boot
sizzle/resources/cljsjs/sizzle/common/sizzle.ext.js

Adds [Sizzle](http://github.com/jquery/sizzle) - A pure JavaScript CSS selector engine designed to be easily dropped in to a host library.

[sizzle] Add sizzle

---

jquery-ui/build.boot

Now pulling from the official jQuery UI site.

Update jQuery UI to 1.11.4

---

dom-delegator/README.md
dom-delegator/build.boot
dom-delegator/resources/cljsjs/dom-delegator/common/dom-delegator.ext.js

Build process modelled after react-timer-mixin.
Closes #408

[dom-delegator] New package, version 13.1.0

---

react-motion/README.md
react-motion/build.boot
react-motion/resources/cljsjs/react-motion/common/react-motion.ext.js

There is a mistyped character in react-motion.ext.js.

[react-motion] Remove a mistyped character

---

firebase/build.boot

Update to firebase 2.4.1 and fix download url

update firebase version, fix url

---

react-select/README.md
react-select/build.boot

As you know I already submitted this patch, but it was based on an old version of the repo. This one should be based on the bleeding edge.

Update react-select beta6 -> beta10

---

typedjs/README.md
typedjs/build.boot
typedjs/resources/cljsjs/typedjs/common/typedjs.ext.js

Add typed.js jQuery plugin

---

react-leaflet/README.md
react-leaflet/build.boot
react-leaflet/resources/cljsjs/common/react-leaflet.ext.js

Hello,
I prepared new script for [react-leaflet](https://github.com/PaulLeCam/react-leaflet) library. 
- package depends on pull request #444 where I upgraded dependencies
- please let me know if externs are OK - it was my first time writing .ext.js file.
Looking forward your feedback,
Dan

[react-leaflet] new package

---

react-bootstrap-datetimepicker/README.md
react-bootstrap-datetimepicker/build.boot
react-bootstrap-datetimepicker/resources/cljsjs/react-bootstrap-datetimepicker/common/react-bootstrap-datetimepicker.ext.js

Add [react-bootstrap-datetimepicker](https://github.com/quri/react-bootstrap-datetimepicker) library to cljsjs

[react-bootstrap-datetimepicker] Create externs

---

leaflet/build.boot
leaflet/resources/cljsjs/common/leaflet.ext.js

Add methods (as documented in http://leafletjs.com/reference.html#latlngbounds) to externs.

Add externs for LatLngBounds methods

---

victory/README.md
victory/build.boot
victory/resources/cljsjs/common/victory.ext.js

CLJSJS package for victory.js (https://github.com/FormidableLabs/victory)

[victory] created new cljsjs package

---

react-input-mask/build.boot

fix react-input-mask

---

react-autosuggest/README.md
react-autosuggest/build.boot
react-autosuggest/resources/cljsjs/react-autosuggest/common/react-autosuggest.ext.js

This is the squashed version the pull request that adds the react-autosuggest library from http://react-autosuggest.js.org/

Added react-autosuggest

---

morphdom/README.md
morphdom/build.boot
morphdom/resources/cljsjs/common/morphdom.ext.js

Add https://github.com/patrick-steele-idem/morphdom
Lightweight module for morphing an existing DOM node tree to match a
target DOM node tree.

[morphdom] new package

---

react-input-mask/build.boot

I'm really really sorry for making third pull request. I promise I'll learn. :)

react-input-mask: fix production file name

---

auth0-lock/README.md
auth0-lock/build.boot
auth0-lock/resources/cljsjs/auth0-lock/common/auth0-lock.ext.js

These externs were missing when I came to use the library in advanced compilation mode.

[auth0-lock] Externs improvement

---

jquery-timepicker/README.md
jquery-timepicker/build.boot
jquery-timepicker/resources/cljsjs/common/jquery-timepicker.ext.js

From https://github.com/jonthornton/jquery-timepicker
Thanks for all the other packages!

Add jquery-timepicker

---

textures/README.md
textures/build.boot
textures/resources/cljsjs/textures/common/textures.ext.js

See: https://riccardoscalco.github.io/textures/

SVG textures for d3

---

moment/build.boot
moment/resources/cljsjs/common/moment.ext.js

http://momentjs.com/docs/#/manipulating/utc-offset/

[moment] add extern for utcOffset()

---

bootstrap-slider/README.md
bootstrap-slider/build.boot
bootstrap-slider/resources/cljsjs/bootstrap-slider/common/bootstrap-slider.ext.js

Add bootstrap-slider library: https://github.com/seiyria/bootstrap-slider

[bootstrap-slider] Add bootstrap-slider

---

material/build.boot
material/resources/cljsjs/material/common/material.ext.js

make externs for objects with methods annotated with @public

Material 1.1.3-1

---

reactable/build.boot
reactable/resources/cljsjs/reactable/common/reactable.ext.js

Adding [Reactable](https://github.com/glittershark/reactable)

[reactable] Adding reactable v0.12.5

---

dragula/README.md
dragula/build.boot
dragula/resources/cljsjs/dragula/common/dragula.ext.js

Add dragula library: https://github.com/bevacqua/dragula

[dragula] Add Dragula

---

smooth-scroll/README.md
smooth-scroll/build.boot
smooth-scroll/resources/cljsjs/smooth-scroll/common/smooth-scroll.ext.js

https://github.com/cferdinandi/smooth-scroll

[smooth-scroll] Add smooth-scroll

---

pinterest/README.md
pinterest/build.boot
pinterest/resources/cljsjs/pinterest/common/pinterest.ext.js
pinterest/resources/deps.cljs

I'm pretty much dipping my toe in the world of github, so if there's something wrong here, please let me know, and I'll remedy asap.
I pretty much copied the facebook package, since the two are so similar. I wasn't certain about the version number, so i used today's date, since that's the sdk that exists today.

pinterest JS sdk externs

---

react-bootstrap/README.md
react-bootstrap/build.boot
react-bootstrap/resources/cljsjs/react-bootstrap/common/react-bootstrap.ext.js

I used the [recommended externs generator](http://jmmk.github.io/javascript-externs-generator/), which seems to identify all elements that had to be inserted manually before.

[react-bootstrap] update to 0.29.2 with react 15

---

react/README.md
react/build.boot

Prepared a new release of React based on [this](https://github.com/facebook/react/releases/tag/v15.0.2)

[react] Upgraded to v15.0.2

---

react-virtualized/README.md
react-virtualized/build.boot
react-virtualized/resources/cljsjs/react-virtualized/common/react-virtualized.ext.js

Adds `react-virtualized` version 6.3.1 w/ externs, boot file, and README
https://github.com/bvaughn/react-virtualized
Addresses my own issue https://github.com/cljsjs/packages/issues/543
**Notes:** Auto generated externs

Add react-virtualized package

---

react-infinite/README.md
react-infinite/build.boot
react-infinite/resources/cljsjs/react-infinite/common/react-infinite.ext.js

Adds `react-infinite` version tag 0.9.0 w/ externs, boot file, and README
https://github.com/seatgeek/react-infinite
**Notes:** Auto generated externs

Add react-infinite package

---

three/build.boot
three/resources/cljsjs/three/common/three.ext.js

The extern generation failed on the Clojurescript generator as it has a known problem with Three. Was successful on Closure Compiler Externs Extractor though and seems to work ok.

[three] Update to R76

---

rangy-core/README.md
rangy-core/build.boot
rangy-core/resources/cljsjs/rangy-core/common/rangy-core.ext.js

The prototype for the Selection object wasn't included in the original externs, so this fixes that issue.

Improve externs for rangy-core

---

filestack/README.md
filestack/build.boot
filestack/resources/cljsjs/filestack/common/filestack.ext.js

This adds [Filestack](https://www.filestack.com/docs/).
Unfortunately they don't version their builds properly so I just used 0.0.1 as version & added a little note about the lack of versioning to the readme.

[filestack] inital

---

auth0-lock/build.boot

Update Auth0-Lock to version 8.3.2 for security patch

---

field-kit/README.md
field-kit/build.boot
field-kit/resources/cljsjs/field-kit/common/field-kit.ext.js

[field-kit](http://square.github.io/field-kit/) is a library for validating/masking text inputs.

[field-kit] Add Square's field-kit library

---

codemirror/README.md
codemirror/build.boot
codemirror/resources/cljsjs/codemirror/common/codemirror.ext.js

Old Externs where incomplete. I started out manually adding them until I realized how many where missing. I decided to generate them and have had no issues so far.

Codemirrow: Generate Externs + bump CLJSJS version

---

mithril/README.md

Lein couldn't find in clojars based on existing spec.
Did a search, found this variant, and at least it downloaded.

[Mithril] Fix version number

---

phoenix/README.md
phoenix/build.boot
phoenix/resources/cljsjs/common/phoenix.ext.js

Add Elixir Phoenix framework client library http://www.phoenixframework.org

[phoenix] Add phoenix library

---

toastr/README.md
toastr/build.boot
toastr/resources/cljsjs/common/toastr.ext.js

Add [toastr](https://github.com/CodeSeven/toastr) 2.1.2 library to cljsjs.

[toastr] Add toastr 2.1.2

---

husl/README.md
husl/build.boot
husl/resources/cljsjs/husl/common/husl.ext.js

Info about the library here:
- http://www.husl-colors.org/
- https://github.com/husl-colors/husl

[husl] Add the HUSL.js color library

---

react-slider/README.md
react-slider/build.boot
react-slider/resources/cljsjs/react-slider/common/react-slider.ext.js

I've tested it locally with all the compiler optimization levels

[react-slider] Add react-slider 0.6.1

---

scrollex/README.md
scrollex/build.boot
scrollex/resources/cljsjs/scrollex/common/scrollex.ext.js

Added jQuery Scrollex plugin v0.2.1
https://github.com/ajlkn/jquery.scrollex

[added] Scrollex

---

rrule/build.boot
rrule/resources/cljsjs/rrule/common/rrule.ext.js

Update:
Includes support for `RRuleSet` and `rrulestr`.

RRule.js prerelease

---

circle.yml

Explicitly set the node version for Circle CI.

Specify node version for circle-ci to latest LTS release

---

react-bootstrap/README.md
react-bootstrap/build.boot

**Extern:** Generated by the package task.

[react-bootstrap] update to 0.29.5

---

material-ui/build.boot

[material-ui] Update to version 0.15.1

---

phoenix/README.md
phoenix/build.boot
phoenix/resources/cljsjs/common/phoenix.ext.js

Update:
**phoenix:1.2.0-0** I updated the extern by hand, to match latest 1.2 version.

Phoenix-1.2.0

---

clusterize/README.md
clusterize/build.boot
clusterize/resources/cljsjs/clusterize/common/clusterize.ext.js

Add clusterize.js

---

showdown/build.boot
showdown/resources/cljsjs/showdown/common/showdown.ext.js

Update:
**Extern:** I updated the extern with generator and minor manual modification (makeHtml)

[showdown] Update to 1.4.2

---

radium/README.md
radium/build.boot
radium/resources/cljsjs/radium/common/radium.ext.js

[radium] Initial commit

---

react-virtualized/README.md
react-virtualized/build.boot

[react-virtualized] Fixed location of minified file

---

react-virtualized/README.md
react-virtualized/build.boot

[react-virtualized] Updated to v7.11.8

---

react/README.md
react/build.boot

[react] Updated react to v15.2.1

---

material-ui/README.md
material-ui/build.boot

[material-ui] Update to version 0.15.2

---

plottable/README.md
plottable/build.boot

Update:
The API did not change.

update plottable to 2.2.0

---

react/resources/cljsjs/react-dom/common/react-dom.ext.js

Update:
Caught these misnamed parameters when compiling.

Update params in react-dom

---

react/README.md
react/build.boot

[react] Upped the cljsjs version to account for new extern

---

d3/README.md
d3/build.boot
d3/resources/cljsjs/d3/common/d3.ext.js

Update:
Updated all `d3-force` objects to have all the appropriate functions and also updated `d3.zoom`.

[d3] Update d3 externs

---

d3-tip/README.md
d3-tip/build.boot
d3-tip/resources/cljsjs/d3-tip/common/d3-tip.ext.js

[d3-tip] Add d3-tip, tooltip plugin for d3

---

react-grid-layout/build.boot

upgrade to react-grid-layout 0.12.7

[react-grid-layout] upgrade to react-grid-layout 0.12.7

---

msgpack-js-browser/README.md
msgpack-js-browser/build.boot
msgpack-js-browser/resources/cljsjs/msgpack-js-browser/common/msgpack-js-browser.ext.js

Add msgpack-js-browser@0.1.4

---

mithril/README.md
mithril/build.boot

Update:
Updated to Mithril 0.2.5

mithril 0.2.5

---

react-select/build.boot

updated react-select to 1.0.0-beta14

---

emojione-picker/README.mdown
emojione-picker/build.boot
emojione-picker/resources/cljsjs/emojione-picker/common/emojione-picker.ext.js

New package:
Add EmojionePicker package.
Here is the original js repo https://github.com/tommoor/emojione-picker

Emojione picker 0.3.6

---

neo4j/README.md
neo4j/build.boot
neo4j/resources/cljsjs/neo4j/common/neo4j.ext.js

[neo4j] Initial commit

---

markdown-it/README.md
markdown-it/build.boot
markdown-it/resources/cljsjs/markdown-it/common/markdown-it.ext.js

[markdown-it] Add markdown-it library

---

react/README.md
react/build.boot
react/resources/cljsjs/react/common/react.ext.js

Update:
I am not a jsdoc expert. So need to check if the extern for [`React.PureComponent`](https://github.com/facebook/react/blob/master/src/isomorphic/modern/class/ReactPureComponent.js) is accurate.
cc @Deraen, @martinklepsch

[react] Updated to v15.3.0

---

reactabular/README.md
reactabular/build.boot
reactabular/resources/cljsjs/reactabular/common/reactabular.ext.js

[reactabular] Updated to v1.0.9

---

d3/README.md
d3/build.boot
d3/resources/cljsjs/d3/common/d3.ext.js

Update:
**Extern:** I updated the extern by hand and with generator.

[d3] Updated to v4.2.0

---

react-sanfona/README.md
react-sanfona/build.boot
react-sanfona/resources/cljsjs/react-sanfona/common/react-sanfona.ext.js

[react-sanfona] Updated to 0.0.13

---

neo4j/README.md
neo4j/build.boot
neo4j/resources/cljsjs/neo4j/common/neo4j.ext.js

[neo4j] Fixed externs

---

pluralize/README.md
pluralize/build.boot
pluralize/resources/cljsjs/pluralize/common/pluralize.ext.js

[pluralize] Added v3.0.0 of the package

---

pickadate/README.md
pickadate/build.boot
pickadate/resources/cljsjs/common/pickadate.ext.js
pickadate/resources/deps.cljs

Adds the pickadate library: http://amsul.ca/pickadate.js/
New package:

[pickadate] Add pickadate library

---

semantic-ui/README.md
semantic-ui/build.boot

[semantic-ui] Update to v2.2.2

---

highlight/README.md

Add instructions on how to add CSS to highlight.js users

[highlight] Add instructions about adding theme CSS to projects

---

material-ui/README.md
material-ui/build.boot

[material-ui] Update to version 0.15.3

---

d3pie/README.md
d3pie/build.boot
d3pie/resources/cljsjs/d3pie/common/d3pie.ext.js

New package: [d3pie](http://d3pie.org/)

[d3pie] Add d3pie package

---

material-ui/README.md
material-ui/build.boot

[material-ui] Update to version 0.15.4

---

react-bootstrap/build.boot
react-bootstrap/resources/cljsjs/react-bootstrap/common/react-bootstrap.ext.js

Update:
I tested this new build with my personal project and it worked.

upgrade react-bootstrap to v0.30.2

---

react/README.md
react/build.boot

[react] Upgraded to 15.3.1

---

recharts/README.md
recharts/build.boot
recharts/resources/cljsjs/recharts/common/recharts.ext.js

[recharts] Add Recharts library

---

stats/README.md
stats/build.boot
stats/resources/cljsjs/stats/common/stats.ext.js

[stats] Add stats.js - a library for JavaScript performance monitor

---

mustache/README.md
mustache/build.boot

[mustache] Update to v2.2.1

---

vega-lite/README.md
vega-lite/build.boot
vega-lite/resources/cljsjs/common/vega-lite.ext.js

Updated the version of vega-lite to 1.2.0
Update:

vega-lite 1.2.0

---

emojione-picker/build.boot
emojione-picker/resources/cljsjs/emojione-picker/common/emojione-picker.ext.js

[emojione-picker] Update emojione-picker

---

highlight/README.md
highlight/build.boot

[highlight] Update to 9.6.0, expand README

---

libphonenumber/README.md
libphonenumber/build.boot
libphonenumber/resources/deps.cljs

**Closure compatible library**, no externs required.
https://github.com/googlei18n/libphonenumber

[libphonenumber] 7.6.0-0: initial release

---

material/build.boot

[material] upgrade to mdl 1.2.0

---

react-select/build.boot
react-select/resources/cljsjs/react-select/common/react-select.ext.js

**Extern:** Added a new component `Select.Creatable`
Also update react and react-input-autosize versions.

[react-select ] Upgrade to 1.0.0-rc.1

---

emojione/README.md
emojione/build.boot

[emojione] Update to version 2.2.6

---

react-flexbox-grid/README.md
react-flexbox-grid/build.boot
react-flexbox-grid/resources/cljsjs/react-flexbox-grid/common/react-flexbox-grid.ext.js
react-flexbox-grid/resources/webpack.config.js

[react-flexbox-grid] 0.10.2-0: initial release

---

pouchdb-find/README.md
pouchdb-find/build.boot
pouchdb-find/resources/cljsjs/pouchdb-find/common/pouchdb-find.ext.js

[pouchdb-find] 0.10.3: initial release

---

react-datetime/README.md
react-datetime/build.boot
react-datetime/resources/cljsjs/react-datetime/common/react-datetime.ext.js

[react-datetime] 2.6.0-0: initial release

---

highcharts/README.md
highcharts/build.boot

[highcharts] Update version

---

pouchdb-live-find/README.md
pouchdb-live-find/build.boot
pouchdb-live-find/resources/cljsjs/pouchdb-live-find/common/pouchdb-live-find.ext.js

[pouchdb-live-find] 0.2.0: initial release

---

react-highlight/README.md
react-highlight/build.boot
react-highlight/resources/cljsjs/react-highlight/common/react-highlight.ext.js
react-highlight/resources/main.js
react-highlight/resources/webpack.config.js

[react-highlight] 1.0.5-0: initial release

---

react-pixi/README.md
react-pixi/build.boot

[react-pixi] Update version

---

reactable/build.boot

Update reactable to version 0.14.0

---

jquery_1/README.md
jquery_1/build.boot
jquery_2/README.md
jquery_2/build.boot

[jquery] Upgrade to 1.12.4 and 2.2.4

---

chartjs/README.md
chartjs/build.boot
chartjs/resources/cljsjs/chartjs/common/chartjs.ext.js

[chartjs] update to v2.3.0

---

react-flexbox-grid/README.md
react-flexbox-grid/build.boot
react-flexbox-grid/resources/cljsjs/react-flexbox-grid/common/react-flexbox-grid.ext.js

[react-flexbox-grid] Fix typo in externs

---

codemirror/README.md
codemirror/build.boot

[codemirror] Update to 5.19

---

highcharts/README.md
highcharts/build.boot
highcharts/resources/cljsjs/highcharts/common/highcharts.ext.js

Update:
**Extern**: Written by hand.
Fix for issues/699

[highcharts] Add attribute series

---

material/build.boot

[material] upgrade to mdl 1.2.1

---

bootstrap-treeview/README.md
bootstrap-treeview/build.boot
bootstrap-treeview/resources/cljsjs/common/bootstrap-treeview.ext.js

Add bootstrap-treeview

---

ajv/README.md
ajv/build.boot

[ajv] Update to 4.7.7

---

react-grid-layout/README.md
react-grid-layout/build.boot
react-grid-layout/resources/cljsjs/react-grid-layout/common/react-grid-layout.ext.js

Update:
Extern: I updated the extern with generator.

[react-grid-layout] upgrade to 0.13.7.

---

auth0-lock/build.boot

Update lock version

---

material-ui/README.md
material-ui/build.boot

[material-ui] Update to version 0.16.0

---

react-motion/build.boot

[react-motion] Update to 0.4.5

---

bootstrap-typeahead/README.md
bootstrap-typeahead/build.boot
bootstrap-typeahead/resources/cljsjs/bootstrap-typeahead/common/bootstrap-typeahead.ext.js

Bootstrap Typeahead

---

accounting/README.md
accounting/build.boot
accounting/resources/cljsjs/accounting/common/accounting.ext.js

[Accounting] Add Accounting.js package

---

accounting/README.md
accounting/build.boot
accounting/resources/cljsjs/accounting/common/accounting.ext.js

Update:
minified build now compiles cleanly

[accounting] Updates externs & bumps version number

---

material-ui/README.md
material-ui/build.boot

[material-ui] Update to version 0.16.1

---

d3/resources/cljsjs/d3/common/d3.ext.js

Update:
**Extern:** I updated the D3 extern by hand.

Added externs for d3.radialLine

---

d3/build.boot
d3/resources/cljsjs/d3/common/d3.ext.js

[d3] Adds ForceNode externs and minor version bump

---

react-bootstrap/README.md
react-bootstrap/build.boot
react-bootstrap/resources/cljsjs/react-bootstrap/common/react-bootstrap.ext.js

[react-bootstrap] update to 0.30.6

---

firebase/build.boot

Update:
**Extern:** provided in source npm zip.

[firebase] Version bump to 3.5.3

---

smoothscroll-polyfill/README.md
smoothscroll-polyfill/build.boot

Polyfill for smoothscroll: http://iamdustan.com/smoothscroll/
New package:
**Extern:** Written by hand. Happens to be blank.

[smoothscroll-polyfill] Add library

---

moment/build.boot
moment/resources/cljsjs/common/moment.ext.js

Update:
**Extern:** Add `defineLocale`

[moment.js] Add missing externs

---

material-ui/README.md
material-ui/build.boot
material-ui/resources/cljsjs/material-ui/common/material-ui.ext.js
material-ui/resources/main.js

[material-ui] Added withWidth

---

moment/build.boot
moment/resources/cljsjs/common/moment.ext.js

[moment] Add isoWeekday extern

---

d3/build.boot
d3/resources/cljsjs/d3/common/d3.ext.js

Add d3.pie's functions to externs

---

libtess/README.md
libtess/build.boot
libtess/resources/cljsjs/libtess/common/libtess.ext.js

Add libtess package

---

material-ui/README.md
material-ui/build.boot

[material-ui] Update to version 0.16.2

---

html2canvas/README.md
html2canvas/build.boot
html2canvas/resources/cljsjs/html2canvas/common/html2canvas.ext.js

[html2canvas] html2canvas library added to cljsjs packages

---

canvas2image/README.md
canvas2image/build.boot
canvas2image/resources/cljsjs/canvas2image/common/canvas2image.ext.js

[canvas2image] canvas2image library added into cljsjs packages

---

material-ui/README.md
material-ui/build.boot

[material-ui] Update to version 0.16.4

---

element-resize-detector/README.md
element-resize-detector/build.boot
element-resize-detector/resources/cljsjs/element-resize-detector/common/element-resize-detector.ext.js

[element-resize-detector] Add version 1.1.9

---

jspdf/build.boot
jspdf/resources/cljsjs/jspdf/common/jspdf.ext.js

[jspdf] missing function added into extern file

---

react-ultimate-pagination/README.md
react-ultimate-pagination/build.boot
react-ultimate-pagination/resources/cljsjs/react-ultimate-pagination/common/react-ultimate-pagination.ext.js
react-ultimate-pagination/resources/webpack.config.js

[react-ultimate-pagination] Initial push 0.8.0

---

vimeo/README.md
vimeo/build.boot
vimeo/resources/cljsjs/common/vimeo.ext.js
vimeo/resources/deps.cljs
youtube/README.md
youtube/build.boot
youtube/resources/cljsjs/common/youtube.ext.js
youtube/resources/deps.cljs

Add vimeo extern.

---

d3/build.boot
d3/resources/cljsjs/d3/common/d3.ext.js

[d3] Add getComputedTextLength for node object

---

download/build.boot
download/resources/cljsjs/download/common/common.ext.js

download 1.4.6

---

highcharts/README.md
highcharts/build.boot
highcharts/resources/cljsjs/highcharts/common/highcharts.ext.js

Add percentage attribute to Highcharts externs

---

lunrjs/README.md

[lunr.js]Update README.md

---

react-datetime/README.md

Add information on how to use this cljsjs component, as the js global is hard to figure out otherwise.

Usage notes for react-datetime

---

tonejs/.gitignore
tonejs/README.md
tonejs/build.boot
tonejs/resources/cljsjs/tonejs/common/Tone.ext.js

Externs for the tonejs (https://github.com/Tonejs/Tone.js) library.
New package:
**Tone.ext.js:** Written (painfully) by hand.

added tonejs

---

tonejs/README.md
tonejs/build.boot

Changed version number in README, fixed original project url

---

codemirror/build.boot
codemirror/resources/cljsjs/codemirror/common/codemirror.ext.js

Added missing showHint extern, bumped version

---

oauthio/README.md
oauthio/build.boot
oauthio/resources/cljsjs/oauthio/common/oauthio.ext.js

[oauthio] Update to v0.6.1, add interfaces

---

preact/README.md
preact/build.boot

[preact] Update version to 7.1.0

---

blend4web/.gitignore
blend4web/README.md
blend4web/build.boot

New package:
**Extern:** Generated (from an existing (non-clojure) project)

Added blend4web externs/support files

---

leaflet/README.md
leaflet/build.boot
leaflet/resources/cljsjs/common/leaflet.ext.js

[leaflet] Add missing L.Icon.Default.imagePath extern

---

material-ui/build.boot
material-ui/resources/cljsjs/material-ui/common/material-ui.ext.js
material-ui/resources/deps.cljs
material-ui/resources/main.js

[material-ui] Update to version 0.16.5, added colorManipulator

---

select2/README.md
select2/build.boot
select2/resources/cljsjs/select2/common/select2.ext.js

[select2] adds select2 4.0.3

---

dygraph/README.md
dygraph/build.boot
dygraph/resources/cljsjs/dygraph/common/dygraph.ext.js

Update:
Generated by http://michaelmclellan.me/javascript-externs-generator/

[dygraph] 1.1.1 externs bugfix - adds missing prototype functions

---

material-ui-chip-input/README.md
material-ui-chip-input/build.boot
material-ui-chip-input/resources/cljsjs/material-ui-chip-input/common/material-ui-chip-input.ext.js
material-ui-chip-input/resources/main.js
material-ui-chip-input/resources/webpack.config.js

[material-ui-chip-input] Initial push 0.11.2

---

react-flip-move/README.md
react-flip-move/build.boot
react-flip-move/resources/cljsjs/react-flip-move/common/react-flip-move.ext.js

Add react-flip-move

---

react-truncate/README.md
react-truncate/build.boot
react-truncate/resources/cljsjs/react-truncate/common/react-truncate.ext.js
react-truncate/resources/webpack.config.js

[react-truncate] Initial push 2.0.3

---

react-google-maps/build.boot
react-google-maps/resources/cljsjs/react-google-maps/common/react-google-maps.ext.js

[react-google-maps] Update package to 6.0.1

---

aws-sdk-js/build.boot
aws-sdk-js/resources/cljsjs/aws-sdk-js/common/aws-sdk-js.ext.js

Update:
**Extern:** I updated the extern by hand to add SQS function declarations

[aws-sdk-js] Added missing function declarations for SQS

---

vis/build.boot
vis/resources/cljsjs/vis/common/vis.ext.js

[vis] Updated to v4.17.0

---

codemirror/README.md
codemirror/build.boot
codemirror/resources/cljsjs/codemirror/common/codemirror.ext.js

[codemirror] Add missing externs for Pos objects

---

reactable/build.boot

Bump version up to 0.14.1 to fix annoying unknown prop warnings
Update:

[reactable] Package update

---

autolayout/README.md
autolayout/build.boot
autolayout/resources/cljsjs/autolayout/common/autolayout.ext.js

New package: [Autolayout.js](http://ijzerenhein.github.io/autolayout.js/)

Add autolayout

---

material-components/README.md
material-components/build.boot
material-components/resources/cljsjs/material-components-web/common/material-components.ext.js

Package Material Design Components for the web

---

material/build.boot

[material] upgrade to mdl 1.3.0

---

preact-compat/README.md
preact-compat/build.boot
preact-compat/resources/cljsjs/preact-compat/common/preact-compat.ext.js
preact-compat/resources/cljsjs/preact-compat/common/react.inc.js
preact-compat/resources/deps.cljs
proptypes/README.md
proptypes/build.boot
proptypes/resources/cljsjs/common/proptypes.ext.js
proptypes/resources/deps.cljs

TODO: Readme and externs (need to copy React externs)

Add preact-compat and proptypes

---

material-components/README.md
material-components/build.boot
material-components/resources/cljsjs/material-components-web/common/material-components.ext.js

Revert "Revert "Package Material Design Components for the web""

---

material-ui/README.md
material-ui/build.boot

[material-ui] Update to version 0.16.6

---

antd/README.md
antd/build.boot
antd/resources/cljsjs/antd/common/antd.ext.js

[antd] update antd to version 2.6.0

---

react-bootstrap/README.md
react-bootstrap/build.boot
react-bootstrap/resources/cljsjs/react-bootstrap/common/react-bootstrap.ext.js

[react-bootstrap] Updated lib to 0.30.7

---

formsy-react/README.md
formsy-react/build.boot
formsy-react/resources/cljsjs/formy-react/common/formsy-react.ext.js

[formsy-react] Initial commit of the package

---

formsy-material-ui/README.md
formsy-material-ui/build.boot
formsy-material-ui/resources/cljsjs/formsy-material-ui/common/formsy-material-ui.ext.js
formsy-material-ui/resources/webpack.config.js

[formsy-material-ui] Initial commit

---

msgpack-lite/README.md
msgpack-lite/build.boot

[msgpack-lite] Update to 0.1.26

---

auth0-lock/README.md
auth0-lock/build.boot
auth0-lock/resources/cljsjs/auth0-lock/common/auth0-lock.ext.js

[auth0-lock] Update to 10.8.1

---

react-virtualized/README.md
react-virtualized/build.boot

[react-virtualized] Add react-dom dependency

---

pdfmake/README.md
pdfmake/build.boot
pdfmake/resources/cljsjs/common/pdfmake.ext.js
pdfmake/resources/deps.cljs

New package:
http://pdfmake.org/

added pdfmake

---

react-modal/README.md
react-modal/build.boot
react-modal/resources/cljsjs/react-modal/common/react-modal.ext.js

very small react library by facebook, added externs by hand (based on react-sticky externs), the component works after an advanced compilation, so as far as I see, it works.
New package:
Extern: Written by hand.
added: squased pull request.

adding react-modal

---

liquidfun/README.md
liquidfun/build.boot
liquidfun/resources/cljsjs/liquidfun/common/liquidfun.ext.js

[liquidfun] Add liquidfun package

---

kjua/README.md
kjua/build.boot
kjua/resources/cljsjs/common/kjua.ext.js
kjua/resources/deps.cljs

added kjua

---

.gitignore
babel-polyfill/README.md
babel-polyfill/build.boot
babel-polyfill/resources/cljsjs/babel-polyfill/common/babel-polyfill.ext.js
zxcvbn/README.md
zxcvbn/build.boot
zxcvbn/resources/cljsjs/zxcvbn/common/zxcvbn.ext.js

Both externs written by hand and tested.

Two new packages: zxcvbn and babel-polyfill

---

material-ui/README.md
material-ui/build.boot
material-ui/resources/cljsjs/material-ui/common/react-dom.ext.js
material-ui/resources/deps.cljs

[material-ui] Add ReactDOM extern

---

material-ui/README.md
material-ui/build.boot

[material-ui] Update to version 0.16.7

---

linkify/README.md
linkify/build.boot
linkify/resources/cljsjs/linkify/common/linkify-element.ext.js
linkify/resources/cljsjs/linkify/common/linkify-html.ext.js
linkify/resources/cljsjs/linkify/common/linkify-jquery.ext.js
linkify/resources/cljsjs/linkify/common/linkify-react.ext.js
linkify/resources/cljsjs/linkify/common/linkify-string.ext.js
linkify/resources/cljsjs/linkify/common/linkify.ext.js
linkify/resources/deps.cljs

[linkify] Initial push 2.1.4

---

web3/README.md
web3/build.boot
web3/resources/deps.cljs

[web3] Update to version 0.18.2

---

leaflet/README.md
leaflet/build.boot
leaflet/resources/cljsjs/common/leaflet.ext.js

Leaflet: I updated the extern by hand.
I've installed the generated .jar locally and have run the resulting optimized code in the browser without issue.

[leaflet] Add Polyline, Polygon, Control, IControl & GeoJson methods

---

clipboard/build.boot

[clipboard]: make sure minified bundle appears in `deps.cljs`

---

aphrodite/build.boot
aphrodite/resources/cljsjs/aphrodite/common/aphrodite.ext.js

New package:
Extern: Generated.

Add aphrodite

---

qart/README.md
qart/build.boot
qart/resources/cljsjs/common/qart.ext.js

New package:
This add [qart.js](https://github.com/kciter/qart.js) packages support.

[qart] Add qart package

---

react-autosuggest/README.md
react-autosuggest/build.boot
react-autosuggest/resources/cljsjs/react-autosuggest/common/react-autosuggest.ext.js

Update: react-autosuggest to 8.0.0 version

[react-autosuggest] Update to 8.0.0 version

---

d3-tip/README.md

Fix d3-tip title

---

inferno/README.md
inferno/build.boot
inferno/resources/cljsjs/inferno/common/inferno.ext.js
inferno/resources/deps.cljs

[inferno] update to 1.2.2 and add inferno-hyperscript

---

incremental-dom/README.md
incremental-dom/build.boot
incremental-dom/resources/gulpfile.js.patch

[incremental-dom] update to 0.5.2

---

d3/build.boot
d3/resources/cljsjs/d3/common/d3.ext.js

Fix error with the scaleSequential externs

---

babel-standalone/README.md
babel-standalone/build.boot
babel-standalone/src/cljsjs/babel_standalone.clj

Package babel-standlone for ClojureScript :preprocess

---

semantic-ui-react/build.boot

Bump semantic-ui-react to 0.65.7

[semantic-ui-react] Bump to 0.64.7

---

openlayers/README.md
openlayers/build.boot

Update openlayers to 4.0.1

---

plotly/README.md
plotly/build.boot
plotly/resources/cljsjs/plotly/common/plotly.ext.js

Update:
add a very simple working example to README.md
**Extern:** I updated the extern with http://jmmk.github.io/javascript-externs-generator

upgrade plotly.js to the latest, 1.22.0

---

slate/README.md
slate/build.boot
slate/resources/cljsjs/slate/common/slate.ext.js

[slate] Upgrade slate version to latest (0.16.17)

---

.gitignore

Ignore the Mac OS .DS_Store files that get created by Finder.

---

smooth-scroll/README.md
smooth-scroll/build.boot

[smooth-scroll] Update smooth-scroll version to 10.2.1

---

codemirror/README.md
codemirror/build.boot
codemirror/resources/cljsjs/codemirror/common/codemirror.ext.js

Update: to latest codemirror release 5.24.0

new version, md5sum, externs

---

material-ui/README.md
material-ui/build.boot

[material-ui] Update to version 0.17.0

---

solidity-sha3/README.md
solidity-sha3/build.boot
solidity-sha3/resources/cljsjs/solidity-sha3/common/solidity-sha3.ext.js
solidity-sha3/resources/main.js
solidity-sha3/resources/webpack.config.js

[solidity-sha3] Initial push 0.4.1

---

react-virtualized/build.boot
react-virtualized/resources/cljsjs/react-virtualized/common/react-virtualized.ext.js

React Virtualized 9.0.3

---

codemirror/README.md
codemirror/build.boot
codemirror/resources/cljsjs/codemirror/common/codemirror.ext.js

Added extern for CodeMirror.defineSimpleMode()

---

material-components/build.boot

Update material components to 0.5.0

---

humane/build.boot

Add default CSS-themes.
Update:

Add default Humane.js CSS-themes

---

iconv-lite/.gitignore
iconv-lite/README.md
iconv-lite/build.boot
iconv-lite/buildjs/build.js
iconv-lite/buildjs/iconv.js
iconv-lite/buildjs/package.json
iconv-lite/resources/cljsjs/iconv-lite/common/iconv-lite.ext.js

add iconv-lite

---

react-chartjs-2/README.md
react-chartjs-2/build.boot
react-chartjs-2/resources/cljsjs/react-chartjs-2/common/react-chartjs-2.ext.js

Add react-chartjs-2

---

moment-timezone/README.md
moment-timezone/build.boot
moment-timezone/resources/cljsjs/common/moment-timezone.ext.js

Add moment timezone
New package:

Add moment timezone package

---

antd/README.md
antd/build.boot
antd/resources/cljsjs/antd/common/antd.ext.js

Update:
Uses the precompiled `antd` with locales so that the `LocaleProvider` component can be used.

[antd] update antd to version 2.8.0

---

dragula/build.boot
dragula/resources/cljsjs/dragula/common/dragula.ext.js

The 'on' function was not declared in the Dragula extern.

[dragula] Add 'on' function to extern for Dragula

---

three/build.boot
three/resources/cljsjs/three/common/three.ext.js

**Extern:** I updated the extern with a generator (same one used in the previous update of three.js).

Updated three.js from r76 to r84

---

benchmark/build.boot
benchmark/resources/cljsjs/benchmark/common/benchmark.ext.js

[benchmark] Add more objects to extern file

---

inferno/README.md
inferno/build.boot

[inferno] update to 1.4.0

---

pdfmake/build.boot

pdfmake update

---

d3/build.boot
d3/resources/cljsjs/d3/common/d3.ext.js

Update:
* Added missing functions to d3.line by hand.

[d3] Add missing d3.line externs by hand

---

iscroll/README.md
iscroll/build.boot
iscroll/resources/cljsjs/iscroll/common/iscroll.ext.js

Create package for IScroll

---

react-datepicker/build.boot
react-onclickoutside/build.boot

Updated react-onclickoutside

---

sticky/README.md
sticky/build.boot
sticky/resources/cljsjs/sticky/common/sticky.ext.js

Create package for sticky-js

---

optiscroll/README.md
optiscroll/build.boot
optiscroll/resources/cljsjs/optiscroll/common/optiscroll.ext.js

Create package for Optiscroll

---

inferno/build.boot

[inferno] update to 1.4.2

---

inferno/README.md
inferno/build.boot

[inferno] update to 1.5.3

---

auth0-lock/README.md
auth0-lock/build.boot
auth0-lock/resources/cljsjs/auth0-lock/common/auth0-lock.ext.js

[auth0-lock] Update to 10.13.0

---

react-virtualized/build.boot
react-virtualized/resources/cljsjs/react-virtualized/common/react-virtualized.ext.js

React Virtualized 9.0.3-1

---

material-components/build.boot
material-components/resources/cljsjs/material-components-web/common/material-components.ext.js

Update Material Components to 0.7.0

---

react-dates/README.md
react-dates/build.boot
react-dates/resources/cljsjs/react-dates/common/react-dates.ext.js

~~Soooo I tried generating externs automatically via https://github.com/jmmk/javascript-externs-generator, but it gave me some nasty output:~~
```<snip>```
~~I'm going to keep trying to figure it out but if you have suggestions let me know. Ideally, I'd like to avoid writing all these externs by hand.~~
I've updated the externs file, let me know if there's anything else you want here.

Bump react-dates to 8.2.1; add a few bits of documentation.

---

fela/README.md
fela/build.boot
fela/resources/cljsjs/fela/common/fela.ext.js

Create package for fela.js

---

fela-dom/README.md
fela-dom/build.boot
fela-dom/resources/cljsjs/fela-dom/common/fela-dom.ext.js

Create package for fela-dom.js

---

fela-plugin-prefixer/README.md
fela-plugin-prefixer/build.boot
fela-plugin-prefixer/resources/cljsjs/fela-plugin-prefixer/common/fela-plugin-prefixer.ext.js

New package: fela-plugin-prefixer.js

Create package for fela-plugin-prefixer.js

---

web3/README.md
web3/build.boot

[web3] Update to version 0.18.4

---

fingerprintjs2/README.md
fingerprintjs2/build.boot
fingerprintjs2/resources/cljsjs/fingerprintjs2/common/fingerprintjs2.ext.js

New package: [fingerprintjs2](https://github.com/Valve/fingerprintjs2)

[fingerprintjs2] add version 1.5.1

---

libphonenumber/README.md
libphonenumber/build.boot

Update libphonenumber to 8.4.0

---

fuse/README.md
fuse/build.boot

[fuse] Update to 2.6.2

---

graphiql/README.md
graphiql/build.boot
graphiql/resources/cljsjs/graphiql/common/graphiql.ext.js

[GraphiQL] Add GraphiQL 0.9.3

---

react-flexbox-grid/build.boot
react-flexbox-grid/resources/cljsjs/react-flexbox-grid/common/react-flexbox-grid.ext.js

[react-flexbox-grid] Update to version 1.0.0

---

package.json
react-xmasonry/README.md
react-xmasonry/build.boot
react-xmasonry/resources/cljsjs/react-xmasonry/common/react-xmasonry.ext.js

Add react-xmasonry

---

inferno/README.md
inferno/build.boot

[inferno] update to 1.6.2

---

clipboard/README.md
clipboard/build.boot
clipboard/resources/cljsjs/clipboard/common/clipboard.ext.js

[clipboard] Update to v1.6.1

---

material-ui/README.md
material-ui/build.boot

[material-ui] Update to version 0.17.3

---

pikaday/build.boot

[pikaday] Update to version 1.5.1

---

material-ui/README.md
material-ui/build.boot

[material-ui] Update to version 0.17.4

---

react-xmasonry/build.boot
react-xmasonry/resources/cljsjs/react-xmasonry/common/react-xmasonry.ext.js

remove duplicate key in externs

---

pikaday/build.boot

Update pikaday to use latest moment

---

twemoji/README.md
twemoji/build.boot
twemoji/resources/cljsjs/twemoji/common/twemoji.ext.js

Add twemoji v2.2.5

---

numeral/README.md
numeral/build.boot
numeral/resources/cljsjs/numeral/common/numeral.ext.js

[numeral] Add library version 2.0.6

---

three-decalgeometry/README.md
three-decalgeometry/build.boot
three-decalgeometry/resources/cljsjs/three-decalgeometry/common/THREE.DecalGeometry.ext.js

Added THREE.DecalGeometry

---

epubjs/README.md
epubjs/build.boot
epubjs/resources/cljsjs/epubjs/common/epub.ext.js
pdfjs/README.md

Add epubjs v0.2.15

---

d3-selection-multi/README.md
d3-selection-multi/build.boot
d3-selection-multi/resources/cljsjs/d3-selection-multi/common/d3-selection-multi.ext.js

d3-selection-multi package: D3 multi-value selection and properties

---

d3/README.md
d3/build.boot
d3/resources/cljsjs/d3/common/d3.ext.js

Add histogram.thresholds extern

---

react-quill/README.md
react-quill/build.boot
react-quill/resources/cljsjs/react-quill/common/react-quill.ext.js

[react-quill] update to v1.0.0-beta-5

---

simplemde/build.boot

fixes typo in upstream url

---

auth0/build.boot
auth0/resources/cljsjs/auth0/common/auth0.ext.js

Update auth0 to 8.6.0

---

react-chartjs-2/build.boot

Update:
Added missing required dependency (ReactDOM)

Fix react-chartjs-2 by adding missing required dependency

---

trello-client/README.md
trello-client/build.boot
trello-client/resources/cljsjs/trello-client/common/trello-client.ext.js
trello-client/resources/deps.cljs

Add the Trello Client library

---

material-ui/README.md
material-ui/build.boot

[material-ui] Update to version 0.18.0

---

google-diff-match-patch/CHANGELOG.md
google-diff-match-patch/README.md
google-diff-match-patch/build.boot
google-diff-match-patch/resources/cljsjs/google-diff-match-patch/common/google-diff-match-patch.ext.js

Update:
My main goal here was to add the minified JavaScript, but I also hand-extracted the ext file from the library because the existing one was missing a few symbols

Google diff match patch/20121119 2

---

react-mdl/README.md
react-mdl/build.boot
react-mdl/resources/cljsjs/react-mdl/common/react-mdl.ext.js

[react-mdl] Updates repository url, Bumps Version, Updates externs

---

material-components/build.boot
material-components/resources/cljsjs/material-components-web/common/material-components.ext.js

[material-components] Update version to 0.10.0 add externs for a few new functions.

---

pixi-sound/README.md
pixi-sound/build.boot
pixi-sound/resources/cljsjs/pixi-sound/common/pixi-sound.ext.js

cljsjs.pixi-sound with minimum externs used in our project like play, add, find etc.
New package:
btw: tried automatic generation but failed.

init cljsjs.pixi-sound

---

react-select/README.md
react-select/build.boot
react-select/resources/cljsjs/react-select/common/react-select.ext.js

Update react select to v1.0.0-rc.3

---

firebase/README.md
firebase/build.boot

Use a variable for the checksum since it changes as often as the
version.
Update:

Version bump firebase to 3.7.3

---

dialog-polyfill/README.md
dialog-polyfill/build.boot

[dialog-polyfill] Update to version 0.4.7

---

antd/README.md
antd/build.boot
antd/resources/cljsjs/antd/common/antd.ext.js

[antd] Update antd to version 2.10.0

---

babel-standalone/build.boot
babel-standalone/src/cljsjs/babel_standalone.clj

New package:
**Empty Extern File:** For dev only. Written by hand.
Update:

Add empty externs file and modify build config for usage in browsers

---

vega/README.md
vega/build.boot
vega/resources/cljsjs/common/vega.ext.js

vega 3.0.0-beta.31

---

material-ui/README.md
material-ui/build.boot

[material-ui] Update to version 0.18.1

---

moment/build.boot
moment/resources/cljsjs/common/moment.ext.js

Add missing Duration constructor

---

semantic-ui-react/build.boot

Ghostandthemachine patch 1

---

react-virtualized/README.md
react-virtualized/build.boot
react-virtualized/resources/cljsjs/react-virtualized/common/react-virtualized.ext.js

upgrade react-virtualized to 9.7.5

---

leaflet/build.boot
leaflet/resources/cljsjs/common/leaflet.ext.js

upgrade to leaflet 1.0.3

---

quill/build.boot
quill/resources/cljsjs/quill/common/quill.ext.js

[quill] update to 1.2.4 version

---

benchmark/build.boot
benchmark/resources/cljsjs/benchmark/common/benchmark.ext.js

[benchmark] Update to v2.1.4

---

resize-observer-polyfill/README.md
resize-observer-polyfill/build.boot
resize-observer-polyfill/resources/cljsjs/resize-observer-polyfill/common/resize-observer-polyfill.ext.js

[resize-observer-polyfill] Add ResizeObserver polyfill

---

styled-classnames/build.boot

[styled-classnames] upgrade to 2.1.3

---

twemoji/README.md
twemoji/build.boot

[twemoji] Update to v2.3.0

---

firebase/README.md
firebase/build.boot

**Extern:** Provided by library.

Update firebase to 4.0.0

---

semantic-ui-react/build.boot

Just version bump and checksum updates

[semantic-ui-react] Bump to 0.68.4

---

fela/build.boot

Update:
**Extern**: The API did not change.

[fela] Update to 4.3.5

---

react-fela/README.md
react-fela/build.boot
react-fela/resources/cljsjs/react-fela/common/react-fela.ext.js

[react-fela] Add 4.3.5

---

react/README.md
react/build.boot
react/resources/cljsjs/react/common/react.ext.js

[react] Add extern for createElement

---

fela-preset-dev/README.md
fela-preset-dev/build.boot
fela-preset-dev/resources/cljsjs/fela-preset-dev/common/fela-preset-dev.ext.js

[fela-preset-dev] Add 4.3.5

---

fela-preset-web/README.md
fela-preset-web/build.boot
fela-preset-web/resources/cljsjs/fela-preset-web/common/fela-preset-web.ext.js

[fela-preset-web] Add 4.3.5

---

highcharts/README.md
highcharts/build.boot
highcharts/resources/cljsjs/highcharts/common/highcharts.ext.js

Update:
Updated the extern with a generator, then did the hand-edits that are mentioned in the extern header. Also verified from the Highcharts API docs that they're still relevant.

[highcharts] Upgrade Highcharts to 5.0.12

---

pixi/README.md
pixi/build.boot
pixi/resources/cljsjs/pixi/common/pixi.ext.js

 [pixi] Upgrade Pixi to 4.5.3

---

react/build.boot

[react] Upgrade to v15.6.0

---

react/README.md
react/build.boot

[react] Update to v15.6.1

---

codemirror/build.boot
highcharts/README.md
highcharts/build.boot

Replaces https://github.com/cljsjs/packages/pull/1217

Package highcharts modules

---

semantic-ui-react/README.md
semantic-ui-react/build.boot

Left everything else untouched

[semantic-ui-react] bump to 0.68.5

---

material-ui/README.md
material-ui/build.boot

[material-ui] Update to version 0.18.3

---

semantic-ui-react/README.md
semantic-ui-react/build.boot

Updated the version and README. Kept the empty externs as I'm still not sure how this magically works

[semantic-ui-react] Bump to 0.70.0

---

react/resources/cljsjs/react/common/react.ext.js

React.Children.toArray: https://facebook.github.io/react/docs/react-api.html#react.children.toarray

[react] Add React.Children.toArray to externs

---

create-react-class/build.boot

[create-react-class] Upgraded to latest release

---

antd/README.md
antd/build.boot
antd/resources/cljsjs/antd/common/antd.ext.js

Update: antd to version 2.11.2

[antd] Update antd to version 2.11.2

---

react-grid-layout/README.md
react-grid-layout/build.boot
react-grid-layout/resources/cljsjs/react-grid-layout/common/react-grid-layout.ext.js

Updated the extern with the generator.

[react-grid-layout] Upgrade react-grid-layout to 0.13.9

---

material-ui/README.md
material-ui/build.boot

[material-ui] Update to version 0.18.6

---

kakao/README.md
kakao/build.boot
kakao/resources/cljsjs/common/kakao.ext.js
kakao/resources/deps.cljs

Added Kakao sdk `cljsjs.kakao`
Extern : failed to generate, written by hand.

[kakao] Add kakao extern

---

vis/README.md
vis/build.boot
vis/resources/cljsjs/vis/common/vis.ext.js

[vis] Update to v4.20.1

---

nvd3/README.md
nvd3/build.boot

[nvd3] Update to version 1.8.5

---

grommet/build.boot

Update to most recent version of Grommet (and react deps)

---

reactcss/README.md
reactcss/build.boot
reactcss/resources/cljsjs/reactcss/common/reactcss.ext.js
reactcss/resources/webpack.config.js

New package:
Note: This library is required by react-color, for which a package will be submitted once this is accepted.

[reactcss] New package - version 1.2.0

---

pixi/build.boot
pixi/resources/cljsjs/pixi/common/pixi.ext.js

erUpdate pixi js to 4.5.4

---

styled-classnames/build.boot

[styled-classnames] upgrade to 2.2.1

---

grommet/build.boot

Upgraded to Grommet 1.6.0

---

material-ui/README.md
material-ui/build.boot

[material-ui] Update to version 0.18.7

---

antd/README.md
antd/build.boot
antd/resources/cljsjs/antd/common/antd.ext.js

[antd] Upgrade to Ant Design 2.12.3

---

ag-grid-enterprise/README.md
ag-grid-enterprise/build.boot
ag-grid-react/README.md
ag-grid-react/build.boot
ag-grid/README.md
ag-grid/build.boot
ag-grid/resources/cljsjs/ag-grid/common/ag-grid.ext.js

upgrading ag-grid, ag-grid-react and ag-grid-enterprise to 12.0.0

---

amazon-cognito-identity-js/README.md
amazon-cognito-identity-js/build.boot
amazon-cognito-identity-js/resources/cljsjs/amazon-cognito-identity-js/common/amazon-cognito-identity-js.ext.js
amazon-cognito-identity-js/resources/deps.cljs

With this PR, I've added support for Amazon's Cognito Identity library: [/aws/amazon-cognito-identity-js](https://github.com/aws/amazon-cognito-identity-js). I tested with both regular and advanced compilation. Additionally, I looked at the last PR by @upgradingdave (#920) and verified that the additional externs from the comments were present.
Thanks!
New package:

Amazon Cognito Identity

---

vega/README.md
vega/build.boot
vega/resources/cljsjs/common/vega.ext.js

vega 3.0.0

---

vega/README.md
vega/build.boot
vega/resources/cljsjs/common/vega.ext.js

Update:
This is my first contribution. Please accept my apologies if there are any problems.

support for vega 3.0.1

---

firebase/build.boot

Update:
Externs are provided upstream

Update firebase to 4.2.0

---

vega-lite/build.boot
vega-lite/resources/cljsjs/common/vega-lite.ext.js

vega-lite 2.0.0-beta14

---

react-autosize-textarea/README.md
react-autosize-textarea/build.boot
react-autosize-textarea/resources/cljsjs/react-autosize-textarea/common/react-autosize-textarea.ext.js
react-autosize-textarea/resources/webpack.config.dist.js

New package:
Signed-off-by: Christian Romney <cromney@pointslope.com>

Added react-autosize-textarea component

---

react-infinite/README.md
react-infinite/build.boot

[react-infinite] Update to version 0.12.1

---

grommet/build.boot

Upgraded to Grommet 1.7.0

---

react-color/README.md
react-color/build.boot
react-color/resources/cljsjs/react-color/common/react-color.ext.js
react-color/resources/main.js
react-color/resources/webpack.config.js

[react-color] New package - version 2.13.1

---

ag-grid-enterprise/README.md
ag-grid-enterprise/build.boot
ag-grid-react/README.md
ag-grid-react/build.boot
ag-grid/README.md
ag-grid/build.boot
ag-grid/resources/cljsjs/ag-grid/common/ag-grid.ext.js

Upgrade to ag-grid, ag-grid-react, ag-grid-enterprise 13.0.1

---

preact-compat/build.boot
preact/build.boot

Update:
**Extern:** The API did not change that I know of.

[preact and preact-compat] bump version to latest release

---

react-tagsinput/README.md
react-tagsinput/build.boot
react-tagsinput/resources/cljsjs/react-tagsinput/common/react-tagsinput.ext.js

react-tagsinput 3.17.0-0

---

react-router/README.md
react-router/build.boot
react-router/resources/cljsjs/react-router/common/react-router.ext.js

Update react-router to 2.6.1-0

---

url-template/README.md
url-template/build.boot
url-template/resources/cljsjs/url-template/common/uri-template.ext.js

Add new package url-template (v2.0.8)

---

d3-tip/build.boot

Also bump d3 dependency to 4.3.0-5 since d3-tip requires that

[d3-tip] Update to 0.7.1

---

highcharts/build.boot

Update to Highcharts 5.0.14.

---

react-datepicker/README.md
react-datepicker/build.boot

Update react-datepicker to 0.54.0 version

Update react-datepicker to 0.54.0 version

---

phoenix/README.md
phoenix/build.boot
phoenix/resources/cljsjs/common/phoenix.ext.js

Externs partially generated by online tool, hand edited for completeness
This is the latest version of the Phoenix Framework's JS client
Update:

[phoenix] Update for Phoenix client v1.3.0

---

pixi/README.md
pixi/build.boot
pixi/resources/cljsjs/pixi/common/pixi.ext.js

PixiJS v4.5.6

---

pouchdb-find/README.md
pouchdb-find/build.boot
pouchdb/README.md
pouchdb/build.boot

updated pouchdb and pouchdb-find to version 6.3.4

---

material-ui/README.md
material-ui/build.boot

[material-ui] Update to version 0.19.2

---

three/README.md
three/build.boot
three/resources/cljsjs/three/common/three.ext.js

Updating to latest three.js version and generating new externs.

---

aframe/README.md
aframe/build.boot
aframe/resources/cljsjs/aframe/common/aframe.ext.js

Also, used a search and replace to change 50 instances of `<x> - <y>` (not valid Javascript) into `['<x>.<y>']`.

Update A-Frame to 0.7.0, fix description

---

highstock/README.md
highstock/build.boot
highstock/resources/cljsjs/common/highstock.ext.js

[highstock] Update to Highstock 5.0.14

---

chess.js/README.md

Add missing foreign libs link

---

antd/README.md
antd/build.boot
antd/resources/cljsjs/antd/common/antd.ext.js

update antd to 2.13.4

---

react-datepicker/README.md
react-datepicker/build.boot
react-datepicker/resources/cljsjs/react-datepicker/common/react-datepicker.ext.js

[react-datepicker] Update to version 0.55.0

---

select2/README.md
select2/build.boot
select2/resources/cljsjs/select2/common/select2.ext.js

Update:
Extern: I updated the extern by hand.

[select2] Add externs

---

howler/README.md
howler/boot-cljsjs-checksums.edn
howler/build.boot
howler/resources/cljsjs/howler/common/howler.ext.js

I've found howler.js to be a simple sound library that "just works". I would like to have it included in cljsjs. 
New package:

initial attempt to add howler to cljsjs

---

leaflet-rotatedmarker/README.md
leaflet-rotatedmarker/build.boot
leaflet-rotatedmarker/resources/cljsjs/leaflet-rotatedmarker/common/leaflet-rotatedmarker.ext.js

This is my first time trying to contribute a cljsjs library so feel free correct anything and everything, not that you should feel any less free had I contributed anything before.
New package:

Added a small extension for leaflet which allows for rotated markers

---

zero-ex/README.md
zero-ex/build.boot
zero-ex/resources/cljsjs/zero-ex/common/0x.ext.js

[zero-ex] upgrade to version 0.21.0

---

openlayers/README.md
openlayers/build.boot

[openlayers] Update OpenLayers to v4.4.1

---

react-grid-layout/boot-cljsjs-checksums.edn
react-grid-layout/build.boot
react-grid-layout/resources/cljsjs/react-grid-layout/common/react-grid-layout.ext.js

React grid layout

---

react-virtualized/README.md
react-virtualized/build.boot
react-virtualized/resources/cljsjs/react-virtualized/common/react-virtualized.ext.js

upgrade react-virtualized to 9.11.1

---

filestack/README.md
filestack/build.boot
filestack/resources/cljsjs/filestack/common/filestack.ext.js

Update:
I updated externs with the clojurescript generator and then added the ones i need by hand since the generator fails to get all the properties.

[filestack] Upgrade to 0.9.9

---

smoothscroll-polyfill/README.md
smoothscroll-polyfill/build.boot
smoothscroll-polyfill/resources/cljsjs/smoothscroll-polyfill/common/smoothscroll_polyfill.ext.js

[smoothscroll-polyfill] Update to 0.4.0 (latest).

---

parinfer-codemirror/README.md
parinfer-codemirror/build.boot
parinfer-codemirror/resources/cljsjs/parinfer-codemirror/common/parinfer-codemirror.ext.js

[parinfer-codemirror] Add 1.4.1

---

parinfer/README.md
parinfer/build.boot
parinfer/resources/cljsjs/parinfer/common/parinfer.ext.js

[parinfer] Update to 3.11.0

---

timeago/README.md
timeago/build.boot
timeago/resources/cljsjs/timeago/common/timeago.ext.js

Add timeago.js

---

moment-timezone/README.md
moment-timezone/build.boot
moment-timezone/resources/cljsjs/common/moment-timezone.ext.js

[moment-timezone] Update externs

---

pixi/README.md
pixi/build.boot
pixi/resources/cljsjs/pixi/common/pixi.ext.js

PixiJS v4.6.0

---

vega-lite/README.md
vega-lite/build.boot
vega-lite/resources/cljsjs/common/vega-lite.ext.js

vega-lite 2.0.0

---

marked/README.md
marked/build.boot
marked/resources/cljsjs/marked/common/marked.ext.js

* marked compile error: 
```clojurescript
(.setOptions js/marked
(clj->js
{:table true
:highlight #(.-value (.highlightAuto js/hljs %))}))
```
```js
marked.Ni({
highlight: function(a) {
return hljs.highlightAuto(a).value
}
});
```

Update marked.ext.js, fixed marked.setOptions  compile error

---

auth0/README.md
auth0/build.boot
auth0/resources/cljsjs/auth0/common/auth0.ext.js

[auth0] Update Auth0.js to 8.10.1

---

semantic-ui-react/README.md
semantic-ui-react/build.boot

[semantic-ui-react] Bump to 0.76.0

---

moment-range/README.md
moment-range/build.boot

Proposed update to the moment-range package so that it is the most up to date version.
Update:

 [moment-range] Completed updates to moment-range package

---

material-components/build.boot
material-components/resources/cljsjs/material-components-web/common/material-components.ext.js

Update:
Rename textfield to textField. Rename MDCTextfield to MDCTextField.
Reference: material-components/material-components-web#1485

Upgrade material components to 0.25.0

---

victory/build.boot

update victory to 0.24.2 from 0.17.0

---

c3/README.md
c3/boot-cljsjs-checksums.edn
c3/build.boot

This mainly fixes bugs: https://github.com/c3js/c3/compare/v0.4.14...v0.4.18
Update:

[c3] Update to 0.4.18

---

pouchdb-authentication/README.md

Update:
**Readme:** I updated the readme by hand.

typo fix in pouchdb authentication package

---

antd/README.md

No change to externs, documentation fix

Update version in README

---

auth0/README.md
auth0/boot-cljsjs-checksums.edn
auth0/build.boot
auth0/resources/cljsjs/auth0/common/auth0.ext.js

Also moving checksums into the new method.
Update:

Updating auth0.js to 8.12.1

---

twemoji/README.md
twemoji/build.boot

[twemoji] Update to v2.4.0

---

ag-grid-enterprise/README.md
ag-grid-enterprise/build.boot
ag-grid-react/README.md
ag-grid-react/build.boot
ag-grid/README.md
ag-grid/build.boot
ag-grid/resources/cljsjs/ag-grid/common/ag-grid.ext.js

Update:
Also needed to manually specify clojure1.8 when building locally, may be some glitch in my local environment.

Upgrade ag-grid, ag-grid-react, ag-grid-enterprise to 15.0.0

---

react-bootstrap-table/build.boot

update lib version

---

firebase/README.md
firebase/boot-cljsjs-checksums.edn
firebase/build.boot

Update firebase to 4.8.1

---

chartjs/boot-cljsjs-checksums.edn
chartjs/build.boot

`boot package install` installs successfully.  This needs to be merged before updating react-chartjs-2 see: https://github.com/cljsjs/packages/pull/1456 .

bump chartjs to 2.7.0

---

react-chartjs-2/boot-cljsjs-checksums.edn
react-chartjs-2/build.boot
react-chartjs-2/resources/cljsjs/react-chartjs-2/common/react-chartjs-2.ext.js

Update react chartjs 2 (redo of #1456)

---

semantic-ui-react/README.md
semantic-ui-react/build.boot

semantic-ui-react update version to 0.77.2

---

pouchdb-authentication/README.md
pouchdb-authentication/build.boot

Just needed to update version and checksums.
`boot package install` executed successfully locally.

Updated to pouchdb-authentification to 1.1.1

---

js-joda/README.md
js-joda/build.boot

upgrade js-joda to 1.6.2

---

iota/README.md
iota/build.boot
iota/resources/cljsjs/iota/common/iota.ext.js

Add IOTA JavaScript library ([iota.lib.js](https://github.com/iotaledger/iota.lib.js)).

Add iota.lib.js

---

react-grid-layout/README.md
react-grid-layout/boot-cljsjs-checksums.edn
react-grid-layout/build.boot

[react-grid-layout] Upgrade react-grid-layout to 0.16.3

---

semantic-ui-react/README.md
semantic-ui-react/boot-cljsjs-checksums.edn
semantic-ui-react/build.boot

[semantic-ui-react] Bump version to 0.78.2

---

react-grid-layout/README.md
react-grid-layout/boot-cljsjs-checksums.edn
react-grid-layout/build.boot
react-grid-layout/resources/cljsjs/react-grid-layout/common/react-grid-layout.ext.js

[react-grid-layout] Upgrade react-grid-layout to 0.16.5

---

raven/README.md
raven/build.boot
raven/resources/cljsjs/raven/common/raven.ext.js

Only one new option in the changelog.

[raven] Upgrade to 3.23.3

---

react-flip-move/README.md
react-flip-move/boot-cljsjs-checksums.edn
react-flip-move/build.boot

[react-flip-move] update to 3.0.1

---

buffer/build.boot

To build/deploy new package in clojars per comments in #1533

[buffer] update version to 5.1.0-1

---

recharts/build.boot

[recharts] Added :global-exports

---

react-sanfona/README.md
react-sanfona/build.boot
react-sanfona/resources/cljsjs/react-sanfona/common/react-sanfona.ext.js

Just your friendly neighborhood upgrade.
Manually updated externs.

[react-sanfona] Upgrade react-sanfona to 1.1.0-0

---

clipboard/README.md
clipboard/build.boot
clipboard/resources/cljsjs/clipboard/common/clipboard.ext.js

Added the 'clearSelection' method which was throwing an exception when used with an advanced compile.

[clipboard] Fix externs

---

react-onclickoutside/README.md
react-onclickoutside/build.boot

Fixing the react.dom require here as well.

[react-onclickoutside] Fix react-dom requirement

---

classnames/README.md
classnames/boot-cljsjs-checksums.edn
classnames/build.boot

Upgrade to latest version and use new checksum validation.

[classnames] Upgrade to 2.2.5

---

react-sanfona/README.md
react-sanfona/boot-cljsjs-checksums.edn
react-sanfona/build.boot

Yet another react-dom -> react.dom fix.
Also bumped react libs to latest CLJSJS patch.

[react-sanfona] Upgrade to 1.2.0

---

react-infinite/README.md
react-infinite/boot-cljsjs-checksums.edn
react-infinite/build.boot

* Bump to React 16 (supports it now)
* Latest deps versions
* Validate checksums
* Proper cljsjs namespacing

[react-infinite] Upgrade react-infinite to 0.13.0

---

react-beautiful-dnd/README.md
react-beautiful-dnd/boot-cljsjs-checksums.edn
react-beautiful-dnd/build.boot

[react-beautiful-dnd] update to 7.0.0

---

draft-js/build.boot

Upgrade draft-js to 0.10.5

---

d3-scale-chromatic/build.boot

Simple one line addition to properly include in does-cljs the requirement for cljsjs.d3 missed during initial package addition.

Added missing require statement missing in desp definition.

---

classnames/build.boot

provide classnames without cljsjs prefix

---

clipboard/README.md
clipboard/build.boot

[clipboard] Update to 2.0.1

---

react-google-maps/README.md
react-google-maps/boot-cljsjs-checksums.edn
react-google-maps/build.boot
react-google-maps/resources/cljsjs/react-google-maps/common/react-google-maps.ext.js

[react-google-maps] Update to 9.4.5

---

react-grid-layout/README.md
react-grid-layout/boot-cljsjs-checksums.edn
react-grid-layout/build.boot

[react-grid-layout] Upgrade react-grid-layout to 0.16.6

---

react-ultimate-pagination/boot-cljsjs-checksums.edn
react-ultimate-pagination/build.boot
react-ultimate-pagination/resources/cljsjs/react-ultimate-pagination/common/react-ultimate-pagination.ext.js

Sorry, this should have been included in #1609 I realize now.

[react-ultimate-pagination] externs fix

---

react-modal/boot-cljsjs-checksums.edn
react-modal/build.boot
react-modal/resources/cljsjs/react-modal/common/react-modal.ext.js

- Updated externs
- Updated dependencies
- Check hashes with validate instead of download :checksum
- Removed unused require

[react-modal] Upgrade react-modal to 3.4.4

---

showdown/boot-cljsjs-checksums.edn
showdown/build.boot

[showdown] update showdown to 1.8.6

---

rc-slider/boot-cljsjs-checksums.edn
rc-slider/build.boot

Version bump and updated checksums.

[rc-slider] Bump to 8.6.1

---

firebase/README.md
firebase/boot-cljsjs-checksums.edn
firebase/build.boot
firebase/resources/deps.cljs

Still a WIP, please don't merge.

[firebase] Update firebase to 5.0.4

---

react-beautiful-dnd/README.md
react-beautiful-dnd/boot-cljsjs-checksums.edn
react-beautiful-dnd/build.boot
react-beautiful-dnd/resources/cljsjs/react-beautiful-dnd/common/react-beautiful-dnd.ext.js

- Updated to latest react-beautiful-dnd 7.1.3 and latest react 16.3.2
- Regenerated externs file

Updated react-beautiful-dnd versions

---

firebase/README.md
firebase/boot-cljsjs-checksums.edn
firebase/build.boot

[firebase] General improvements/fixes to build.boot

---

react-sanfona/README.md
react-sanfona/boot-cljsjs-checksums.edn
react-sanfona/build.boot

[react-sanfona] Upgrade to 1.2.2

---

moment/README.md
moment/boot-cljsjs-checksums.edn
moment/build.boot
moment/resources/cljsjs/common/moment.ext.js

Upgraded to 2.22.2 and:
* Added a validation step to Boot file
* Re-generated externs automatically
* Double-checked hand-added externs (they did not change)

[moment] Upgrade to 2.22.2

---

slate/README.md
slate/boot-cljsjs-checksums.edn
slate/build.boot

Also did some cleanup to Boot file and added validation.

[slate] Upgrade Slate to 0.33.6

---

dexie/README.md
dexie/boot-cljsjs-checksums.edn
dexie/build.boot
dexie/resources/cljsjs/common/dexie.ext.js

- Improve extern coverage enough for general use
- Update to the latest Dexie version (2.0.4)
Tested locally and it works (can create a db, put objects in tables, and retrieve them).

[dexie] Upgrade to 2.0.4

---

flatpickr/README.md
flatpickr/boot-cljsjs-checksums.edn
flatpickr/build.boot

This is the final v3 release, which, among other things, fixed some bugs in 3.0.5.
v4 is packaged a bit differently, so will be a bit more work/testing to package, so rather do that later.

[flatpickr] Updated to 3.1.5

---

semantic-ui/README.md
semantic-ui/boot-cljsjs-checksums.edn
semantic-ui/build.boot

bumping to 2.3.1, switching deprecated :checksum option to validate task

---

semantic-ui-react/README.md
semantic-ui-react/boot-cljsjs-checksums.edn
semantic-ui-react/build.boot

Bump to 0.81.1

---

js-joda-timezone/README.md
js-joda-timezone/build.boot

create new package js-joda-timezone

---

xlsx/README.md
xlsx/boot-cljsjs-checksums.edn
xlsx/build.boot
xlsx/resources/cljsjs/xlsx/common/xlsx.ext.js
xlsx/resources/main.js
xlsx/resources/package.json

This adds in the [xlsx library](https://github.com/SheetJS/js-xlsx) from [SheetJS](https://sheetjs.com/).

[xlsx] Adds in xlsx library

---

semantic-ui-react/README.md

semantic-ui-react: Use examples from developers blog

---

react-datetime/README.md
react-datetime/boot-cljsjs-checksums.edn
react-datetime/build.boot

Updates react-datetime from 2.8.10 to 2.14.0.

[react-datetime] Update to 2.14.0

---

semantic-ui-react/README.md
semantic-ui-react/boot-cljsjs-checksums.edn
semantic-ui-react/build.boot

Update Semantic-UI-React from 0.81.1 to 0.82.0

[semantic-ui-react] Update to 0.82.0

---

sinon/README.md
sinon/boot-cljsjs-checksums.edn
sinon/build.boot

* Bump sinon version to 6.1.4
* Update pom :url
* Switch from :checksum to (validate-checksums)
* Added boot-cljsjs-checksums.edn
* Update README with new createFakeServer signature

[sinon] Bump to 6.1.4

---

raven/build.boot

See https://circleci.com/gh/cljsjs/packages/3489

[raven] Fix the package upgrade

---

jquery-confirm/README.md
jquery-confirm/boot-cljsjs-checksums.edn
jquery-confirm/build.boot
jquery-confirm/resources/cljsjs/jquery-confirm/common/jquery-confirm.ext.js

[jquery-confirm] Add package

---

amazon-cognito-identity-js/README.md
amazon-cognito-identity-js/build.boot
amazon-cognito-identity-js/resources/cljsjs/amazon-cognito-identity-js/common/amazon-cognito-identity-js.ext.js

bumped to latest version and regenerated externs

[amazon-cognito-identity-js] Update to 1.31.0-0

---

react-player/boot-cljsjs-checksums.edn
react-player/build.boot

[react-player] Update to 1.6.4

---

leaflet-polylinedecorator/README.md
leaflet-polylinedecorator/build.boot
leaflet-polylinedecorator/resources/cljsjs/leaflet-polylinedecorator/common/leaflet-polylinedecorator.ext.js

I put externs in leaflet externs because I don't know how to extend L (if it is possible at all).
It does work for my use case (adding leaflet + polylinedecorator) and using it.

[leaflet-polylinedecorator] Add leaflet-polylinedecorator

---

material-ui_1/README.md

Docs: Update link

---

firebase/README.md
firebase/build.boot

Bump firebase version

---

html-screen-capture/README.md
html-screen-capture/boot-cljsjs-checksums.edn
html-screen-capture/build.boot
html-screen-capture/resources/cljsjs/html-screen-capture/common/html-screen-capture.ext.js

Adding `html-screen-capture-js` package, from cdn source with externs.

[html-screen-capture] Add package

---

lz-string/README.md
lz-string/boot-cljsjs-checksums.edn
lz-string/build.boot
lz-string/resources/cljsjs/lz-string/common/lz-string.ext.js

Adding `lz-string` package, with externs and cdn source.

[lz-string] Add package

---

html-screen-capture/README.md
lz-string/README.md

Fix package name in `html-screen-capture` REAMDE and a minor fix to `lz-string` README.

[lz-string][html-screen-capture] Fix readmes

---

redux/boot-cljsjs-checksums.edn
redux/build.boot

[redux] Update to 4.0.0

---

material-ui_1/boot-cljsjs-checksums.edn

I realized I forgot to update the checksums for my PR yesterday.  Sorry about that.  I just ran `boot package install target` in the `material-ui_1` repo to fix it.

Use correct checksums

---

js-joda/build.boot
js-joda/resources/cljsjs/js-joda/common/js-joda.ext.js

upgrade js-joda to version 1.9.2

---

twemoji/README.md
twemoji/boot-cljsjs-checksums.edn
twemoji/build.boot

Update:
Extern: The API did not change.

[twemoji] Update to v11.2.0

---

pouchdb-find/README.md
pouchdb-find/build.boot

Update to 7.0.0

---

bootstrap-typeahead/build.boot

bumped up to recent jQuery version

---

pouchdb-find/build.boot
pouchdb/README.md
pouchdb/build.boot

Update all references to 7.0.0

---

dom-to-image/README.md
dom-to-image/build.boot

[dom-to-image] Add package

---

pikaday/build.boot

[pikaday] Update to version 1.8.0

---

semantic-ui-react/README.md
semantic-ui-react/boot-cljsjs-checksums.edn
semantic-ui-react/build.boot

[semantic-ui-react] upgrade to v0.83.0

---

js-joda-locale-en-us/README.md
js-joda-locale-en-us/build.boot
js-joda-locale-en-us/resources/cljsjs/js-joda-locale-en-us/common/js-joda-locale.ext.js
js-joda-timezone/README.md
js-joda-timezone/build.boot
js-joda/README.md

new js-joda locale package and bump js-joda tz package

---

moment/build.boot
moment/resources/cljsjs/common/moment.ext.js

updateLocale function was mangled with advanced compilation.
The prototype is auto-generated but adding singular block for this
doesn't sound feasible either.
Cheers

[Moment] Add updateLocale to ext.js

---

leaflet/resources/cljsjs/leaflet/common/leaflet.ext.js

Not a systematic update, I just noticed this one function was not included.

[leafletjs] Add Map.flyToBounds

---

vega-lite/build.boot
vega-lite/resources/cljsjs/vega-lite/common/vega-lite.ext.js
vega/build.boot
vega/resources/cljsjs/vega/common/vega.ext.js

Compiled against Vega 4.3.0-0 (see #1747).

[vega-lite] update vega-lite version to 3.0.0-rc8-0

---

semantic-ui/README.md
semantic-ui/boot-cljsjs-checksums.edn
semantic-ui/build.boot
semantic-ui/resources/cljsjs/semantic-ui/common/semantic-ui.ext.js

Also adds extern declaration for new `placeholder` component.

[semantic-ui] Update to v2.4.1

---

react-table/README.md
react-table/boot-cljsjs-checksums.edn
react-table/build.boot
react-table/resources/cljsjs/react-table/common/react-table.ext.js

[react-table] add react table package with version 6.8.6

---

recharts/README.md
recharts/boot-cljsjs-checksums.edn
recharts/build.boot
recharts/resources/cljsjs/recharts/common/recharts.ext.js

[recharts] Update to v1.4.2

---

ag-grid-community/README.md
ag-grid-community/build.boot
ag-grid-community/resources/cljsjs/ag-grid-community/common/ag-grid-community.ext.js
ag-grid-enterprise/README.md
ag-grid-enterprise/build.boot
ag-grid-react/README.md
ag-grid-react/build.boot
ag-grid-react/resources/webpack.config.js

This adds version 19.0.0 of ag-grid-community, ag-grid-enterprise and ag-grid-react.

[ag-grid] Add ag-grid community, enterprise and react version 19.0.0

---

pdfjs/boot-cljsjs-checksums.edn
pdfjs/build.boot
pdfjs/resources/cljsjs/pdfjs/common/pdf.ext.js
pdfjs/resources/deps.cljs

[pdfjs] Update pdfjs

---

react-test-renderer/README.md
react-test-renderer/boot-cljsjs-checksums.edn
react-test-renderer/build.boot
react-test-renderer/resources/cljsjs/react-test-renderer/common/react-test-renderer.ext.js

What the commit says. I picked the version to match react-renderer-shallow.  If there's interest, I'll update both in a later commit.

Initial import of react-test-renderer.

---

material-ui-icons/README.md

docs(material-ui-icons): update link

---

react-popper/boot-cljsjs-checksums.edn
react-popper/build.boot
react-popper/resources/cljsjs/react-popper/common/react-popper.ext.js

Updating to the latest react-popper.

updating to latest reactpopper

---

react-datepicker/boot-cljsjs-checksums.edn
react-datepicker/build.boot
react-datepicker/resources/cljsjs/react-datepicker/common/react-datepicker.ext.js

Updating to the latest version

Updating to latest react-datepicker.

---

webtorrent/boot-cljsjs-checksums.edn
webtorrent/build.boot
webtorrent/resources/cljsjs/webtorrent/common/webtorrent.ext.js

* Updates build.boot, removes static checksum, adds validates-checksum.
* Adds checksum edn file.
* Updates externs file.

[WebTorrent] Updates webtorrent to 0.103.0

---

anime/boot-cljsjs-checksums.edn
anime/build.boot

* Refactors and Updates build.boot
* Removes static checksum for download and instead checksums the js file.
* Adds checksum edn file.

[anime] Updates anime build.boot

---

mousetrap/boot-cljsjs-checksums.edn
mousetrap/build.boot

* Refactors build.boot package task code.
* Adds boot checksum edn.

[mousetrap] Updates build.boot

---

phoenix/boot-cljsjs-checksums.edn
phoenix/build.boot

* Updates to release 1.4.1 in build.boot
* Adds checksum edn file.
* Minor refactor to the package deftask

[Phoenix] Updates Phoenix client framework to 1.4.1

---

react-day-picker/README.md
react-day-picker/boot-cljsjs-checksums.edn
react-day-picker/build.boot

[react-day-picker] Fix Exception in dev-mode

---

react-beautiful-dnd/README.md
react-beautiful-dnd/boot-cljsjs-checksums.edn
react-beautiful-dnd/build.boot
react-beautiful-dnd/resources/cljsjs/react-beautiful-dnd/common/react-beautiful-dnd.ext.js

[react-beautiful-dnd] Updates react-beautiful-dnd to 10.0.4

---

react-draggable/README.md
react-draggable/boot-cljsjs-checksums.edn
react-draggable/build.boot
react-draggable/resources/cljsjs/react-draggable/common/react-draggable.ext.js

[react-draggable] Updated to 3.2.1

---

vega-lite/build.boot
vega/boot-cljsjs-checksums.edn
vega/build.boot

[vega-lite] update vega-lite to 3.0.2-0

---

react-datepicker/boot-cljsjs-checksums.edn
react-datepicker/build.boot
react-datepicker/resources/cljsjs/react-datepicker/common/react-datepicker.ext.js

Updated react-datepicker to the newest version of the library.

[react-datepicker] Update react-datepicker to latest version 2.3.0

---

vega/boot-cljsjs-checksums.edn
vega/build.boot

Update to most recent Vega version

[vega] update vega version to 5.3.4-0

---

react-player/README.md
react-player/boot-cljsjs-checksums.edn
react-player/build.boot
react-player/resources/cljsjs/common/react-player.ext.js

Upversion react-player to 1.11.0. Checklist was followed.

[react-player] Upversion to 1.11.0

---

body-scroll-lock/README.md
body-scroll-lock/boot-cljsjs-checksums.edn
body-scroll-lock/build.boot
body-scroll-lock/resources/cljsjs/body-scroll-lock/common/body-scroll-lock.ext.js

Adds the `body-scroll-lock` library cljsjs package (https://github.com/willmcpo/body-scroll-lock).
Tested locally.

Add package for `body-scroll-lock` library

---

fixed-data-table-2/README.md
fixed-data-table-2/boot-cljsjs-checksums.edn
fixed-data-table-2/build.boot
fixed-data-table-2/resources/cljsjs/fixed-data-table/common/fixed-data-table.ext.js

[fixed-data-table-2] Upgrade to 0.8.23.

---

react-giphy-selector/boot-cljsjs-checksums.edn
react-giphy-selector/build.boot
react-giphy-selector/resources/cljsjs/react-giphy-selector/common/react-giphy-selector.ext.js

Updated the package version and updated the externs manually since it was only added a new property.

[react-giphy-selector] Update to version 0.0.3.

---

esri-leaflet/README.md
esri-leaflet/boot-cljsjs-checksums.edn
esri-leaflet/build.boot
esri-leaflet/resources/cljsjs/esri-leaflet/common/esri-leaflet.ext.js

Add the esri-leaflet plugin in the latest verion (2.2.4)

Add esri-leaflet

---

material-ui/README.md
material-ui/boot-cljsjs-checksums.edn
material-ui/build.boot
material-ui/resources/cljsjs/material-ui/common/material-ui.ext.js
material-ui/resources/package.json

[material-ui] Updated to 4.1.0

---

bootstrap/build.boot

[bootstrap] Update library to version 3.4.1

---

material-ui/README.md
material-ui/boot-cljsjs-checksums.edn
material-ui/build.boot
material-ui/resources/package.json

[material-ui] Updated to 4.1.2

---

material-ui/README.md
material-ui/boot-cljsjs-checksums.edn
material-ui/build.boot
material-ui/resources/package.json

[material-ui] Updated to 4.1.3

---

ag-grid-react/build.boot

There are bugs when they are mismatched (e.g. sorting isn't working)

[ag-grid-react] Update dependency on ag-grid-community

---

material-ui/README.md
material-ui/boot-cljsjs-checksums.edn
material-ui/build.boot
material-ui/resources/cljsjs/material-ui/common/material-ui.ext.js
material-ui/resources/package.json

[material-ui] Updated to 4.2.0

---

material-ui/README.md
material-ui/boot-cljsjs-checksums.edn
material-ui/build.boot
material-ui/resources/package.json

[material-ui] Updated to 4.2.1

---

material-ui/README.md
material-ui/boot-cljsjs-checksums.edn
material-ui/build.boot
material-ui/resources/package.json

[material-uí] Updated to 4.3.2

---

material-ui/README.md
material-ui/boot-cljsjs-checksums.edn
material-ui/build.boot
material-ui/resources/package.json

[material-ui] Updated to 4.3.3

---

sentry-browser/boot-cljsjs-checksums.edn
sentry-browser/build.boot
sentry-browser/resources/cljsjs/sentry-browser/common/sentry-browser.ext.js

Upgraded version and externs using the javascript externs generator.

[sentry-browser] Upgrade from 5.4.3 to 5.6.2.

---

material-ui/README.md
material-ui/boot-cljsjs-checksums.edn
material-ui/build.boot
material-ui/resources/package.json

[material-ui] Updated to 4.4.0

---

mousetrap/README.md
mousetrap/boot-cljsjs-checksums.edn
mousetrap/build.boot

[mousetrap] Updated to 1.6.3

---

material-ui/README.md
material-ui/boot-cljsjs-checksums.edn
material-ui/build.boot
material-ui/resources/package.json

[material-ui] Updated to 4.4.1

---

react-draggable/README.md
react-draggable/boot-cljsjs-checksums.edn
react-draggable/build.boot

[react-draggable] Updated to 3.3.2

---

react-sortable-hoc/boot-cljsjs-checksums.edn
react-sortable-hoc/build.boot

Update to 1.10.1. unpkg path has changed.

[react-sortable-hoc] Updated to 1.10.1

---

material-ui/README.md
material-ui/boot-cljsjs-checksums.edn
material-ui/build.boot
material-ui/resources/package.json

[material-ui] Updated to 4.4.3

---

js-dataverse/README.md
js-dataverse/boot-cljsjs-checksums.edn
js-dataverse/build.boot
js-dataverse/resources/cljsjs/js-dataverse/common/js-dataverse.ext.js
js-dataverse/resources/main.js
js-dataverse/resources/package.json
js-dataverse/resources/webpack.config.js

cljsjs/axios https://github.com/cljsjs/packages/pull/1973 is required for it
Did it for https://github.com/cljsjs/packages/issues/1972

[js-dataverse] Created with version 1.0.17

---

react-stripe-elements/boot-cljsjs-checksums.edn
react-stripe-elements/build.boot
react-stripe-elements/resources/cljsjs/react-stripe-elements/common/react-stripe-elements.ext.js

[react-stripe-elements] Upgrade to v5.0.1

---

react-bootstrap/README.md
react-bootstrap/boot-cljsjs-checksums.edn
react-bootstrap/build.boot
react-bootstrap/resources/cljsjs/react-bootstrap/common/react-bootstrap.ext.js

[react-bootstrap] Updated to 1.0.0-beta.14-0.

---

leaflet-pixi-overlay/README.md
leaflet-pixi-overlay/boot-cljsjs-checksums.edn
leaflet-pixi-overlay/build.boot
leaflet-pixi-overlay/resources/cljsjs/leaflet-pixi-overlay/common/leaflet-pixi-overlay.ext.js

This adds a new leaflet-overlay.

Adding leaflet-pixi-overlay

---

leaflet-heatmapjs/README.md
leaflet-heatmapjs/boot-cljsjs-checksums.edn
leaflet-heatmapjs/build.boot
leaflet-heatmapjs/resources/cljsjs/leaflet-heatmapjs/common/leaflet-heatmapjs.ext.js

Plugin for leaflet to use heatmaps
Requires: #1978

Add leaflet-heatmapjs

---

react/resources/cljsjs/react/common/react.ext.js

[React] Fix version comment

---

material-ui/README.md
material-ui/boot-cljsjs-checksums.edn
material-ui/build.boot
material-ui/resources/package.json

[material-ui] Updated to 4.6.0

---

react-tooltip-lite/README.md
react-tooltip-lite/boot-cljsjs-checksums.edn
react-tooltip-lite/build.boot
react-tooltip-lite/resources/cljsjs/react-tooltip-lite/common/react-tooltip-lite.ext.js

[react-tooltip-lite] Updated to 1.10.0

---

sentry-browser/README.md
sentry-browser/boot-cljsjs-checksums.edn
sentry-browser/build.boot

[sentry-browser] Update to 5.10.2

---

react-toastify/README.md
react-toastify/boot-cljsjs-checksums.edn
react-toastify/build.boot
react-toastify/resources/package.json

[react-toastify] Updated to 5.5.0

---

vega/boot-cljsjs-checksums.edn
vega/build.boot
vega/resources/cljsjs/vega/common/vega.ext.js

Updates to most recent Vega version

[vega] update vega version to 5.9.0-0

---

react-virtualized/README.md
react-virtualized/boot-cljsjs-checksums.edn
react-virtualized/build.boot

[react-virtualized] Updated to 9.21.2

---

material-ui/README.md
material-ui/boot-cljsjs-checksums.edn
material-ui/build.boot
material-ui/resources/package.json

[material ui] Updated to 4.9.5

---

material-ui-lab/README.md
material-ui-lab/boot-cljsjs-checksums.edn
material-ui-lab/build.boot
material-ui-lab/resources/cljsjs/material-ui-lab/common/material-ui-lab.ext.js
material-ui-lab/resources/main.js
material-ui-lab/resources/package.json
material-ui-lab/resources/webpack.config.js

Hi,
I have added `material-ui-lab` package since it has some useful components. This is my first contribution to this repository, so please check if I have done everything correctly.

Added package material-ui-lab

---

material-ui-chip-input/README.md
material-ui-chip-input/boot-cljsjs-checksums.edn
material-ui-chip-input/build.boot
material-ui-chip-input/resources/cljsjs/material-ui-chip-input/common/material-ui-chip-input.ext.js
material-ui-chip-input/resources/main.js
material-ui-chip-input/resources/package.json
material-ui-chip-input/resources/webpack.config.js

Updating config and removing no longer needed AutoComplete dependency.

---

webcola/README.md
webcola/build.boot
webcola/resources/cljsjs/webcola/common/cola.ext.js

Add the webcola force-directed graph layout library

---

material-table/README.md
material-table/boot-cljsjs-checksums.edn
material-table/build.boot
material-table/resources/cljsjs/material-table/common/material-table.ext.js
material-table/resources/main.js
material-table/resources/package.json
material-table/resources/webpack.config.js

Hi,
I have added material-table package. @nohaapav asked for it and also it is a nice component that I will probably use and hopefully many others.

Added package material-table

---

material-ui/README.md
material-ui/boot-cljsjs-checksums.edn
material-ui/build.boot
material-ui/resources/package.json

[material-ui] Updated to 4.9.12

---

blueprintjs-core/README.md
blueprintjs-core/boot-cljsjs-checksums.edn
blueprintjs-core/build.boot
blueprintjs-core/resources/package.json
blueprintjs-datetime/README.md
blueprintjs-datetime/boot-cljsjs-checksums.edn
blueprintjs-datetime/build.boot
blueprintjs-datetime/resources/package.json

[blueprintjs-core] Updated to 3.26.0 and [blueprintjs-datetime] Updated to 3.16.1

---

react-day-picker/README.md
react-day-picker/boot-cljsjs-checksums.edn
react-day-picker/build.boot
react-day-picker/resources/cljsjs/react-day-picker/react-day-picker.ext.js

[react-day-picker] Updated to 7.4.8

---

react-draggable/README.md
react-draggable/boot-cljsjs-checksums.edn
react-draggable/build.boot
react-draggable/resources/cljsjs/react-draggable/common/react-draggable.ext.js

[react-draggable] Updated to 4.3.1

---

html2canvas/README.md
html2canvas/boot-cljsjs-checksums.edn
html2canvas/build.boot

[html2canvas] Updated to 1.0.0-rc.5

---

react-autosuggest/README.md
react-autosuggest/boot-cljsjs-checksums.edn
react-autosuggest/build.boot

[react-autosuggest] Updated to 10.0.2

---

oidc-client/README.md
oidc-client/build.boot
oidc-client/resources/cljsjs/oidc-client/common/oidc-client.ext.js

Bumps `oidc-client` to the most recent version (`1.10.1`).

[oidc-client] Bump to 1.10.1

---

CODEOWNERS
konami/README.md
konami/boot-cljsjs-checksums.edn
konami/build.boot
konami/resources/cljsjs/konami/common/konami.ext.js

Hi,
This PR introduces [konami-js](http://snaptortoise.github.io/konami-js/) library to the CLJSJS project. The library adds the konami code easter egg to the project. I used it in a couple of Clojure project I figured that it can be added to CLJSJS. 
The boot build script was tested locally. Also the resulting jar was tested in an independent project.
Regards,
Dejan.

[konami] Introduce konami library

---

js-joda-locale-en-us/build.boot

provide global export for js-joda-locale

---

noty/README.md

Inform user that css file comes separately.

---

react-flip-move/README.md
react-flip-move/boot-cljsjs-checksums.edn
react-flip-move/build.boot

[react-flip-move] Update to 3.0.4

---

re-resizable/README.md
re-resizable/boot-cljsjs-checksums.edn
re-resizable/build.boot
re-resizable/resources/package.json

[re-resizable] Updated to 6.5.0

---

react-toastify/README.md
react-toastify/boot-cljsjs-checksums.edn
react-toastify/build.boot
react-toastify/resources/package.json

[react-toastify] Updated to 6.0.5

---

blueprintjs-core/README.md
blueprintjs-core/boot-cljsjs-checksums.edn
blueprintjs-core/build.boot
blueprintjs-core/resources/package.json

[blueprintjs-core] Updated to 3.28.2

---

blueprintjs-datetime/README.md
blueprintjs-datetime/boot-cljsjs-checksums.edn
blueprintjs-datetime/build.boot
blueprintjs-datetime/resources/package.json

[blueprintjs-datetime] Updated to 3.18.2

---

react-window/README.md
react-window/boot-cljsjs-checksums.edn
react-window/build.boot

Patch release to remove the source map reference.

[react-window] Remove sourcemap line

---

popperjs-core/README.md
popperjs-core/boot-cljsjs-checksums.edn
popperjs-core/build.boot

[popperjs-core] Upgrade popperjs-core to 2.4.4

---

highcharts/README.md
highcharts/build.boot
highcharts/resources/cljsjs/highcharts/common/highcharts.ext.js

Add the exportChart function to externs

[highcharts] Add exportChart to externs

---

downshift/README.md
downshift/boot-cljsjs-checksums.edn
downshift/build.boot
downshift/resources/cljsjs/downshift/common/downshift.ext.js

Add support for downshift: https://github.com/downshift-js/downshift

 [downshift] Add downshift package

---

react-toastify/README.md
react-toastify/boot-cljsjs-checksums.edn
react-toastify/build.boot
react-toastify/resources/package.json

[react-toastify] Updated to 6.0.9

---

react-virtualized/README.md
react-virtualized/boot-cljsjs-checksums.edn
react-virtualized/build.boot

[react-virtualized] Updated to 9.22.2

---

blueprintjs-core/README.md
blueprintjs-core/boot-cljsjs-checksums.edn
blueprintjs-core/build.boot
blueprintjs-core/resources/package.json

[blueprintjs-core] Updated to 3.34.0

---

blueprintjs-datetime/README.md
blueprintjs-datetime/boot-cljsjs-checksums.edn
blueprintjs-datetime/build.boot
blueprintjs-datetime/resources/package.json

[blueprintjs-datetime] Updated to 3.19.3

---

highlight/README.md
highlight/boot-cljsjs-checksums.edn
highlight/build.boot
highlight/resources/cljsjs/common/highlight.ext.js

[highlight] Updated to 10.3.1

---

highcharts/README.md
highcharts/boot-cljsjs-checksums.edn
highcharts/build.boot
highcharts/resources/cljsjs/highcharts/common/highcharts.ext.js

[highcharts] updated to 8.2.2

---

vega-embed/README.md
vega-embed/build.boot
vega-lite/README.md
vega-lite/build.boot
vega-tooltip/README.md
vega-tooltip/build.boot
vega/README.md
vega/boot-cljsjs-checksums.edn
vega/build.boot

Update vega stuff

---

rc-slider/README.md
rc-slider/boot-cljsjs-checksums.edn
rc-slider/build.boot
rc-slider/resources/webpack.config.js
re-resizable/README.md
re-resizable/boot-cljsjs-checksums.edn
re-resizable/build.boot
re-resizable/resources/webpack.config.js
react-toastify/README.md
react-toastify/boot-cljsjs-checksums.edn
react-toastify/build.boot
react-toastify/resources/package.json
react-toastify/resources/webpack.config.js

Fix some react packages which packed react into bundle

---

re-resizable/README.md
re-resizable/boot-cljsjs-checksums.edn
re-resizable/build.boot
re-resizable/resources/package.json

[re-resizable] Updated to 6.6.1

---

react-tagcloud/README.md

[react-tagcloud] Fixing readme example

---

blockly/README.md
blockly/build.boot

Update Blockly to version 5.20210325.1

---

wordcloud2/boot-cljsjs-checksums.edn
wordcloud2/build.boot

Bump wordcloud2 version

---

oidc-client/README.md
oidc-client/boot-cljsjs-checksums.edn
oidc-client/build.boot
oidc-client/resources/cljsjs/oidc-client/common/oidc-client.ext.js

Oidc client

---

fraction/README.md
fraction/boot-cljsjs-checksums.edn
fraction/build.boot
fraction/resources/package.json

Updates the fraction package to 4.1.1. Thank you!

Update fraction package to 4.1.1

---

tabulator/README.md
tabulator/boot-cljsjs-checksums.edn
tabulator/build.boot

[tabulator] Updated to 4.9.3

---

leaflet-markercluster/README.md
leaflet-markercluster/boot-cljsjs-checksums.edn
leaflet-markercluster/build.boot

[leaflet-markercluster] bump to latest

---

firebase/README.md
firebase/boot-cljsjs-checksums.edn
firebase/build.boot

upgrade firebase version to 9.6.8

upgrade version of firebase to 9.6.8

---

material-ui/resources/cljsjs/material-ui/common/material-ui.ext.js

[material-ui] Fix ext

---

react-toastify/README.md
react-toastify/boot-cljsjs-checksums.edn
react-toastify/build.boot
react-toastify/resources/package.json
react-toastify/resources/webpack.config.js

[react-toastify] Updated to 9.0.5

---

re-resizable/README.md
re-resizable/boot-cljsjs-checksums.edn
re-resizable/build.boot
re-resizable/resources/package.json

[re-resizable] Updated to 6.9.9

---

react/README.md
react/boot-cljsjs-checksums.edn
react/build.boot
react/resources/cljsjs/react-dom/common/react-dom-server.ext.js
react/resources/cljsjs/react/common/react.ext.js

[react] Updated to 18.0.0

---

react/README.md
react/boot-cljsjs-checksums.edn
react/build.boot

[react] Updated to 18.1.0

---

react/README.md
react/boot-cljsjs-checksums.edn
react/build.boot

[react] Updated to 18.2.0

---

openlayers-ol-ext/README.md
openlayers-ol-ext/boot-cljsjs-checksums.edn
openlayers-ol-ext/build.boot
openlayers/README.md
openlayers/boot-cljsjs-checksums.edn
openlayers/build.boot

Update openlayers and openlayerer ol-ext

---

js-joda-timezone/README.md
js-joda-timezone/build.boot

[js-joda-timezone] Updated to 2.17.2

---

highcharts-react-official/README.md
highcharts-react-official/boot-cljsjs-checksums.edn
highcharts-react-official/build.boot
highcharts-react-official/resources/cljsjs/highcharts-react-official/common/highcharts-react-official.ext.js

[highcharts-react-official] Update to version 3.2.0

---

date-fns/README.md
date-fns/boot-cljsjs-checksums.edn
date-fns/build.boot
date-fns/resources/main.js
date-fns/resources/package.json

[date-fns] Updated to 2.30.0

---

twilio-voice-sdk/README.md
twilio-voice-sdk/boot-cljsjs-checksums.edn
twilio-voice-sdk/build.boot
twilio-voice-sdk/resources/cljsjs/twilio-voice-sdk/common/twilio-voice-sdk.ext.js

[twilio-voice-sdk] Update to v2.4.0

---

vega-embed/README.md
vega-embed/build.boot

[vega-embed] Update to 6.22.2

---

vega/README.md
vega/boot-cljsjs-checksums.edn
vega/build.boot

[vega] Update to 5.25.0

---

js-joda-timezone/README.md
js-joda-timezone/boot-cljsjs-checksums.edn
js-joda-timezone/build.boot

The wrong file-name was the cause.
Also took the chance to add the validation step.

[js-joda-timezone] Fix deps.cljs missing minified js

---

js-joda/README.md
js-joda/build.boot

[js-joda] Updated to 5.6.3

---

js-joda-locale-fr-fr/README.md
js-joda-locale-fr-fr/build.boot
js-joda-locale-fr-fr/resources/cljsjs/js-joda-locale-fr-fr/common/js-joda-locale.ext.js

[js-joda-locale-fr-fr] Add js-joda-locale-fr-fr package

---

js-joda-timezone/README.md
js-joda-timezone/boot-cljsjs-checksums.edn
js-joda-timezone/build.boot

[js-joda-timezone] Updated to 2.21.1
