cljsjs/packages

- moment/README.md
- moment/build.boot
- moment/resources/cljsjs/common/moment.ext.js
This is working for me within an adapted version of @martinklepsch 's testbed. I've updated the externs file to include moment.locale(...) introduced in 2.8.1.
> produce a moment.js 2.9.0 build

- chance/build.boot
- chance/resources/cljsjs/common/chance.ext.js
- chance/resources/deps.cljs
I had to leave out chance.min.js.  It has to be generated with `grunt uglify`.  It cannot be retrieved from the github releases or the npm registry.
> add chancejs package

- google-maps/resources/cljsjs/common/google_maps_api_v3.ext.js
The README file states that it is 3.18, but the actual externs were for 3.15.
3.18 includes many new features that are now covered by this externs file.
The externs file was taken from https://github.com/google/closure-compiler/blob/master/contrib/externs/maps/google_maps_api_v3_18.js
> Update google-maps to 3.18

- mui/README.md
- mui/build.boot
This uses the `:no-externs` option from `deps-cljs` that's still unreleased assuming that it will be on `cljsjs/boot-cljsjs "0.4.7"`.
> Adding Mui package

- heap/README.md
- heap/build.boot
- heap/resources/cljsjs/common/heap.ext.js
- heap/resources/deps.cljs
Heap JS currently doesn't define a version number. I discussed with heap guys and then will consider it in the future.
For now I just used `1.0.0`. As you can't choose your JS file but have to use whatever their latest is I don't think it is a problem.
> [heap] Added 1.0.0

- firebase/resources/cljsjs/common/firebase.ext.js
checkVars defaults to ERROR
>> tmp/bower_components/firebase-extern/index.js:13: ERROR - Variable Firebase first declared in tmp/bower_components/firebase-extern/index.js
>> var Firebase = function(firebaseURL) {};
> Fix firebase extern compile error.

- codemirror/README.md
- codemirror/build.boot
CodeMirror comes with a large list of addons that can be opted in to. In
the previous version these weren't being packaged, now they are.
> [codemirror] Bump version to 5.6.0, also package addons

- codemirror/README.md
- codemirror/build.boot
The mode js regex was matching both modes and their tests. When tests
were present this was causing the mode test files to overwrite the modes
themselves sometimes (depending on sort order I think).
> Fix Codemirror mode tests overwriting modes in some cases

- material/README.md
- material/build.boot
This updates material to the latest version.  It also moves it over to the github's releases, which have published checksums.
> Update material to 1.0.6

- react-bootstrap/README.md
- react-bootstrap/build.boot
- react-bootstrap/resources/cljsjs/react-bootstrap/common/react-bootstrap.ext.js
This PR builds on a previous open PR, https://github.com/cljsjs/packages/pull/264, which is needed to be compatible with the version of React (0.14) that's currently in CLJSJS.
> [react-bootstrap] update deps to cljsjs.react 0.14.0-1 and fix a comment

- react-bootstrap/README.md
- react-bootstrap/build.boot
- react-bootstrap/resources/cljsjs/react-bootstrap/common/react-bootstrap.ext.js
The old 0.25.2 version is no longer working with the new react 0.14.0 releases.  See https://github.com/react-bootstrap/react-bootstrap#react-v013-support
Most of the changes in the externs file seem due to ongoing library reorganization.
> [react-bootstrap] Update to v0.27.1

- codemirror/README.md
- codemirror/build.boot
In addition to the upgrade, also includes the previously missing `theme` directory's CSS files in the final jar.
> Update codemirror to 5.8.0

- snapsvg/README.md
- snapsvg/build.boot
- snapsvg/resources/cljsjs/snapsvg/common/snapsvg.ext.js
This PR adds a CLJSJS package for [Snap.svg](http://snapsvg.io/).
I ported one of their demos to ClojureScript and the result can be found [here](http://diegonc.github.io/tests/snapsvg/clock/dist/public/). You can clone/browse my [`diegonc.github.io`](https://github.com/diegonc/diegonc.github.io) repository to look at the sources (sorry for the code style, it's not very functional).
It's a dependency of [react-burger-menu](https://github.com/negomi/react-burger-menu) for which I also have a branch and will make a pull request if Snap is merged.
> snapsvg: add package version 0.4.1-0

- react-burger-menu/README.md
- react-burger-menu/build.boot
- react-burger-menu/resources/cljsjs/react-burger-menu/common/react-burger-menu.ext.js
This is the React component [react-burger-menu](http://negomi.github.io/react-burger-menu/) packaged for ClojureScript.
I generated the externs using one of the online tool and the upstream provided example, after being ported to cljs, still [works](http://diegonc.github.io/tests/react-burger-menu/om-example/dist/public/).
Note that the zip is downloaded from **branch 1.1.6** because I found some [errors](https://github.com/negomi/react-burger-menu/issues/23) in the distributed files and the author fixed it in that branch.
So, while tag _v1.1.6_ exists, it's broken and should not be used to download the zip file.
> react-burger-menu: add version 1.1.6-0

- react-sanfona/README.md
- react-sanfona/build.boot
- react-sanfona/resources/cljsjs/react-sanfona/common/react-sanfona.ext.js
react-sanfona is an accordion component for React.
This PR packages version 0.0.4, the latest one written for React 0.13.x.
> react-sanfona: version 0.0.4-0

- mathbox/README.md
- mathbox/build.boot
- mathbox/resources/cljsjs/mathbox/common/mathbox.ext.js
By request from a couple of people in the cljs community, with the blessing of the MathBox author, and in preparation for putting a cljs wrapper for it onto Clojars, I've added a [MathBox](https://github.com/unconed/MathBox.js/tree/legacy) package.
This is my first time using boot (and my first contribution to CLJSJS), so feedback and critique would be much appreciated if anyone has any.
> [mathbox] Create MathBox package

- spin/README.md
- spin/build.boot
- spin/resources/cljsjs/spin/common/spin.ext.js
Added a package for spin.js, which is a simple utility for creating progress spinners. Tested locally. Have not contributed any cljsjs packages before, but followed the "Creating Packages" walkthrough. Hopefully everything is ok.
> New package for spin.js

- codemirror/README.md
- codemirror/build.boot
update codemirror version to 5.10.0
pulls deps packages properly running `boot package`
> update codemirror version

- jquery/README.md
Due to the way this is packaged, the `[](dependecy)` section has not been automatically updated.
> Mention actual latest version in README

- react-select/build.boot
What is says on the tin. Without this dependency you get `Uncaught TypeError: Cannot read property 'findDOMNode' of undefined` when navigating the select box with the arrow keys, which leads to broken scrolling.
I haven't tested this locally, since `boot package build-jar` fails with
```
➜  react-select git:(react-select-dom) boot package build-jar
clojure.lang.ExceptionInfo: java.lang.IllegalArgumentException: No such task (build-jar)
data: {:file
"/var/folders/t2/bmq0l4f516789351wk6b_sgh0000gn/T/boot.user3216260690496726718.clj",
:line 21}
java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: No such task (build-jar)
java.lang.IllegalArgumentException: No such task (build-jar)
boot.core/construct-tasks  core.clj:  754
...
clojure.core/apply  core.clj:  630 …
```
> Add react-dom as dependency for react-select

- leaflet/resources/cljsjs/common/leaflet.ext.js
This PR adds missing [clearLayers](http://leafletjs.com/reference.html#layergroup-clearlayers) and [addData](http://leafletjs.com/reference.html#geojson-adddata) to leaflet externs file
> Add methods clearLayers and addData to leaflet externs

- quill/build.boot
- quill/resources/cljsjs/quill/common/quill.ext.js
The top-level Quill namespace wasn't properly declared and also there were multiple extraneous function externs with multiple arities.
> Fix quill externs issues

- react-bootstrap/README.md
- react-bootstrap/build.boot
- react-bootstrap/resources/cljsjs/react-bootstrap/common/react-bootstrap.ext.js
Just keeping this up-to-date.  This patch updates to the latest bootstrap and react-bootstrap, using the latest cljsjs/react-dom dependency.  Changes to externs reflect some reorganization in the upstream project primarily related to navbar components.
> [react-bootstrap] Update to v0.28.1

- auth0-lock/build.boot
Fixes #365 As explained in my comment in that issue, extern file has not been updated because the API seems to have remained the same.
> Update auth0-lock to most recent version (v8.1.5)

- bytebuffer/README.md
- bytebuffer/build.boot
- long/README.md
- long/build.boot
- Update long.js to latest upstream lib. 
- Update bytebuffer.js to use latest long.js.
> Update long.js and bytebuffer.js.

- tv4/README.md
- tv4/build.boot
- tv4/resources/cljsjs/tv4/common/tv4.ext.js
[tv4](https://github.com/geraintluff/tv4) is a JavaScript library for validating [JSON Schema](http://json-schema.org) validation, based on v4 of the specification.
Closes https://github.com/okal/cljsjs-packages/issues/1
> Package tv4 for cljsjs

- react-datepicker/build.boot
I'm getting errors on the old version, checking to see if a newer version fixes it.
> Upgrade react-datepicker

- react-input-mask/build.boot
It used to point to 'http://https://...', which is ill-formed.
> Fixed project url for react-input-mask

- react-motion/build.boot
- react-motion/resources/cljsjs/react-motion/common/react-motion.ext.js
This PR still has a few issues:
* The react-motion release archive no longer includes the built js file, apparently it is now only served via `npmcdn.com`. I changed the package task to download from there but the task fails with:
clojure.lang.ExceptionInfo: javax.net.ssl.SSLException: Received fatal alert: internal_error
Not sure if this an error on my end or with java and `npmcdn.com`. I did however put the js file on my own http server for testing and the download task worked as expected.
* The minify task fails on my rig with:
clojure.lang.ExceptionInfo: java.lang.IllegalArgumentException: No implementation of method: :file of protocol: #'boot.tmpdir/ITmpFile found for class: nil
Looks like it can't find the input file, the sift task correctly moved the file though.
Removing the …
> [react-motion] Update to 0.4.1

- react/README.md
If you have transitive dependencies on cljsjs/react, such as through
om/reagent, you need to tell lein/boot that cljsjs/react is being
provided for, or it will include react.inc.js instead of
react-with-addons.inc.js. I've updated the readme to reflect this.
Also, I don't know if this applies to boot, so I've left that out. If someone knows more I can add it in. This "fixes" #390.
> [React] updated readme to include exclusion hint

- chartist/build.boot
- chartist/resources/cljsjs/common/chartist.ext.js
The API is `Line`; the extern has `Linex`. Likely a typo.
> [chartist] Fix chartist Line extern

- codemirror/build.boot
meta.js lives in the root of the mode directory rather than a
subdirectory, so it is not picked up by the regular mode regex. It is
not itself a mode - it contains function to map extensions, mime types,
and names to modes.  However, since it is closely related to modes and
it seems unlikely there will ever be a "meta" mode I think it makes
sense to place it under cljsjs.codemirror.mode in the namespace
hierarchy. I'm open to suggestions on the placement though if anyone
has other suggestions.
> [codemirror] Add mode/meta.js

- react-grid-layout/README.md
- react-grid-layout/build.boot
- react-grid-layout/resources/cljsjs/react-grid-layout/common/react-grid-layout.ext.js
There was one part I was not completely sure about. Grid elements can have a magic prop, called `_grid`, that gets used by ReactGridLayout. So we don't want it to get compiled away in our source.
https://github.com/STRML/react-grid-layout#usage
So I put it on `React.ReactAttribute`, just like the `key` prop.
https://github.com/cljsjs/packages/blob/master/react/resources/cljsjs/react/common/react.ext.js#L282
I'm not sure if this is the correct way to do it.
> [react-grid-layout] bump to version 0.10.8

- react-input-mask/build.boot
react-input-mask now uses ES6 in sources and provides separate build file
> fix react-input-mask

- filesaverjs/README.md
1) nonexistent lib version -> latest version from clojars;
2) in example Blob options must be converted to JS object too
> [filesaverjs] fix README issues

- google-diff-match-patch/README.md
- google-diff-match-patch/build.boot
The distributed minified version of the library is missing a semi-colon that causes a cryptic error message when you use more than one cljsjs package in a project, didn't notice until now.
> Fix google-diff-match-patch production build

- vega-lite/README.md
- vega-lite/build.boot
- vega-lite/resources/cljsjs/common/vega-lite.ext.js
- vega/README.md
- vega/build.boot
* updates vega to 2.5.0
* add vega-lite as a separate package, which depends on vega
> update vega and add vega-lite

- platform/README.md
- platform/build.boot
- platform/resources/cljsjs/platform/common/platform.ext.js
This is the library that you need to use google's oauth2 authentication. There are some quirks. It seems that Google wants to force you to use their CDN and does not have a public repo or github repo for this library. Therefore the version that I mention is bogus (google does not externally version this) and it may break unexpectedly. When this occurs, an easy fix is described in the README
> add google platform library (for authentication)

- chartist/build.boot
- chartist/resources/cljsjs/common/chartist.ext.js
this extends the chartist externs in two ways:
1. try to get to something "as complete as possible" using [a generator](http://jmmk.github.io/javascript-externs-generator/)
2. add interpolation functions that are missing from externs otherwise
> [chartist] extend externs

- photoswipe/README.md
- photoswipe/build.boot
- photoswipe/resources/cljsjs/photoswipe/common/photoswipe.ext.js
http://photoswipe.com
Photoswipe splits its default UI javascript into a separate file, so here I'm generating a second entry into the `:foreign-libs` key of `deps.cljs` for `cljsjs.photoswipe-ui-default`.
> Add Photoswipe library

- material-ui/README.md
- material-ui/build.boot
- material-ui/resources/cljsjs/material-ui/common/material-ui-svg-icons.ext.js
- material-ui/resources/cljsjs/material-ui/common/material-ui.ext.js
- material-ui/resources/deps.cljs
- material-ui/resources/webpack.config.js
> added material-ui

- material-ui/README.md
- material-ui/build.boot
- material-ui/resources/cljsjs/material-ui/common/material-ui.ext.js
- material-ui/resources/cljsjs/react-dom/common/react-dom.ext.js
- material-ui/resources/cljsjs/react/common/react.ext.js
- material-ui/resources/deps.cljs
- material-ui/resources/main.js
- material-ui/resources/webpack.config.js
Currently, material-ui has to be built together with react, otherwise [react-tap-event-plugin](https://github.com/zilverline/react-tap-event-plugin) doesn't work. So this build includes `react` `react.dom` `react-tap-event-plugin` `material-ui`. This should not be needed in a future.
> Updated version and added react to the build

- react-grid-layout/README.md
- react-grid-layout/build.boot
- react-grid-layout/resources/cljsjs/react-grid-layout/common/react-grid-layout.ext.js
Updates `react-grid-layout` to the latest release, `0.12.3`. Requires an upgrade of react to `15.0.2`.
**Note:**  Auto-generated a new externs file and placed the directions that I used to generate it. I'm not quite sure how the previous externs was generated.
> [react-grid-layout] Update to version 0.12.3

- bcrypt/README.md
- bcrypt/build.boot
- bcrypt/resources/cljsjs/bcrypt/common/bcrypt.ext.js
Adds `bcrypt` version 2.3.0 the latest tagged release.
Notes: The provided externs in the library itself seemed to be out of date. I updated it via a hand rolling but was tested with optimizations `:none` and `:advanced`. It exposes the lib thru js/dcodeIO so I added an example in the README.md about that.
> Adds bcrypt library version 2.3.0

- lamejs/README.md
- lamejs/build.boot
- lamejs/resources/cljsjs/lamejs/common/lamejs.ext.js
This adds a `cljsjs.lamejs` package for a fast MP3 encoder written purely in JavaScript.
> Add lamejs package with build.boot, ext file and a README

- react/README.md
* Explain that this goes in your ClojureScript compiler options.
* Add `:file` key also; without this, the compiler throws a NullPointerException.
> Improve explanation of using TestUtils

- autobahnjs/README.md
Took me a while to figure out why I was getting `no such namespace` issues. The README.md is just wrong.
> fix library require name

- c3/README.md
- c3/build.boot
This updates c3 to version [0.4.11](https://github.com/c3js/c3/releases/tag/0.4.11).
> [c3] Update c3 to 0.4.11

- victory/build.boot
- victory/resources/cljsjs/common/victory.ext.js
Without the cljsjs.react requirement, the library used to fail to load for me, even if I added it to my project's `:dependencies` separately.
> upgrade to latest upstream version, add react requirement

- victory/build.boot
- victory/resources/cljsjs/common/victory.ext.js
VictoryLine is broken in 0.7.0 and 0.8.0.  Lacking the ability to plot lines would be more crippling than missing anything in these newer versions.
It seems that the only new extern since 0.6.1 is `VictorySharedEvents`, so I've commented out its entry for the time being.
```diff
es@bocha:~/src/victory/src$ git diff v0.6.1 -- index.js
diff --git a/src/index.js b/src/index.js
index 3313e5c..8b24dbb 100644
--- a/src/index.js
+++ b/src/index.js
@@ -1,7 +1,8 @@
import {
VictoryAnimation,
VictoryLabel,
-  VictoryTransition
+  VictoryTransition,
+  VictorySharedEvents
} from "victory-core";
import {
@@ -29,5 +30,6 @@ export {
VictoryPie,
VictoryScatter,
VictoryStack,
-  VictoryTransition
+  VictoryTransition,
+  VictorySharedEvents
};
```
> downgrade to 0.6.1 until VictoryLine gets fixed

- victory/build.boot
- victory/resources/cljsjs/common/victory.ext.js
This version fixes the problem with VictoryLine which had us pinning this library to v0.6.1.
Update:
> upgrade victory.js to v0.9.0

- aws-sdk-js/build.boot
The production path for aws-sdk-js.min.js has a hyphen where there should be a dot, and as a result there is no production folder in the release.
> aws-sdk-js: Fix production aws-sdk.min.js path

- vega/README.md
- vega/build.boot
- vega/resources/cljsjs/common/vega.ext.js
Update:
As far as I can tell, the API did not actually change with this release, but the externs file for the previously packaged version was already out-of-date.
> [vega] Update to 2.6.0

- pdfjs/README.md
- pdfjs/build.boot
- pdfjs/resources/cljsjs/pdfjs/common/pdf.ext.js
A couple of manual adjustments to re-order entries so the diff isn't so scary, and to correct workerSrc attribute which the generator mistakenly classed as a fn.
This also removes a number of externs. These weren't exposed in 1.1.3 nor are they in current 1.5.188, so they seem to have been mistakenly added. The then/cancel/getPage/getViewport properties are to the promise returned from .getDocument; not from pdfjs per se. AnnotationUtils/DefaultTextLayerFactory seems to come from viewer.js, not exported in the dist pdf.js.
> [pdf.js] Update to release 1.5.188

- typeahead-bundle/build.boot
Update:
**Dependencies:** added dependency on jQuery.
Typeahead depends on jQuery. If the dependency declaration is missing in the package, typeahead might break because it gets loaded before jQuery.
> [typeahead-bundle] Add dependency on jquery

- fixed-data-table/build.boot
> [fixed-data-table] Release 0.6.3

- pickadate/build.boot
I realized that the css files included for pickadate where just labelled
"classic.css" and "default.css", which wasn't descriptive names for the files.
> [pickadate] Prefix pickadate css files with "pickadate"

- msgpack-js-browser/build.boot
- msgpack-js-browser/resources/cljsjs/msgpack-js-browser/common/msgpack-js-browser.ext.js
I missed `var` causing syntax warnings in advanced compilation mode.
Update:
> Fix compiler warnings

- react-burger-menu/build.boot
Update:
Not bumping all the way to latest v1.10.2 since that now depends on snapsvg-cjs which is a re-packaging of snapsvg & I think that violates the "no package against forks".
The radium dependency is now required at runtime.
> [react-burger-menu] update to v1.9.9

- react-onclickoutside/build.boot
I referenced `cljsjs.object-assign-shim` in the deps-cljs, but did not include it in the actual dependencies at the top of the file. This should fix the bug reported in slack with the react-datepicker version 0.28.2 where someone had to manually include `[cljsjs/object-assign-shim "0.1.0-0"]` to use that version
Update:
> [react-onclickoutside] Add missing dependency

- raven/build.boot
- raven/resources/cljsjs/raven/common/raven.ext.js
- react-input-mask/README.md
- react-input-mask/build.boot
react-input-mask 0.7.2:
raven 3.5.1:
**Extern:** Updated.
> react-input-mask, raven

- react-datepicker/build.boot
Fixes #703. Forgot to update this when I bumped the version in #689 -
whoops!
Update:
> [react-datepicker] Update to latest react-onclickoutside

- d3/resources/cljsjs/d3/common/d3.ext.js
Issue #707 refers
I'm not sure I'm properly respecting the externs conventions here but happy to adjust if not.
> Add x0, x1, y0 and y1 accessors to d3.area object

- react-onclickoutside/README.md
- react-onclickoutside/build.boot
Dependency `cljsjs/object-assign-shim` has two published versions on Clojars: [`0.1.0-0`](https://clojars.org/cljsjs/object-assign-shim/versions/0.1.0-0) and [`0.1.0-1`](https://clojars.org/cljsjs/object-assign-shim/versions/0.1.0-1).
As far as I can tell, looking at the content of the published jars, the only difference is that `0.1.0-1` inlcludes `deps.cljs`, where `0.1.0-0` does not.  Obviously it would be nice for `react-onclickoutside` to use the version which does have `deps.cljs` for all its automagical goodness.
Update:
> [react-onclickoutside] Bump dep object-assign-shim

- object-assign-shim/README.md
- object-assign-shim/build.boot
This version has already been deployed to Clojars, but the version number here in the repo never got updated.  There are no changes to the actual code, the only difference between `0.1.0-0` and `0.1.0-1` in Clojars is that the latter's artifact contains `deps.cljs`
Update:
> [object-assign-shim] Bump version to match Clojars

- react-datepicker/README.md
- react-datepicker/build.boot
Update:
The `0.28.2-1` bundle doesn't include CSS, because the CSS-generating portion of the build fails, because the dependency used to generate it isn't properly installed.
> [react-datepicker] Fix CSS generation

- highstock/build.boot
- highstock/resources/cljsjs/common/highstock.ext.js
Update:
**build.boot:**
Changed `:download` task from `http` to `https`.
**Extern:** 
One API item was added at `4.2.4` [changelog](http://www.highcharts.com/documentation/changelog#highstock)
I updated the extern by hand.
**Comments:**
Should we also update highcharts in unison? I took a look at the [changelog](http://www.highcharts.com/documentation/changelog) and there's quite a bit of additional configurations added, but those configs don't need to be listed in the externs file. 
One piece I wasn't quite sure about (relating to high*charts* not high*stock* is the `chart.events`. The existing externs file doesn't list anything related, so I'm not sure if it's not needed or it was missing the whole time. Perhaps @jimlar can comment?
> [highstock] 4.2.2->4.2.6

- react-datepicker/README.md
- react-datepicker/build.boot
Update:
Looking at the changelog it seems like 0.29.0 just has minor changes
over 0.28.2, but I can't get the extern generator tool to work correctly
so that I can verify it.  I tried out my local build and the produced
Maven artifact can be imported and works just fine.
> [react-datepicker] Update to 0.29.0

- react/README.md
Correct README for using react TestUtils with advanced optimization. The :provides value of the :foreign-libs declaration should match what's in deps.cljs.
> [react] Fix README typeo for minified TestUtils

- fuse/README.md
- fuse/build.boot
(e.g. Extern), if none of choices is valid you should probably do
Update:
Extern: The API did not change.
Thanks,
Ryan
> Update Fuse to v2.5.0

- bootstrap-toggle/README.md
- bootstrap-toggle/build.boot
- bootstrap-toggle/resources/cljsjs/bootstrap-toggle/common/bootstrap-toggle.ext.js
The extern file was incorrect, as it was listing internal functions rather than the single publicly-visible function that the library intends you to use.
> Fix bootstrap-toggle externs

- material-ui/build.boot
- material-ui/resources/cljsjs/material-ui/common/material-ui.ext.js
Update:
Using filter options for the autocomplete field caused render errors with enabled advanced compilation.
> [material-ui] Fix missing extern for autocomplete filter options

- quill/README.md
- quill/build.boot
- quill/resources/cljsjs/quill/common/quill.ext.js
This fixes a problem where Quill would complain about its themes not being registered
> [quill] Externs were not correct for Quill themes

- clipboard/build.boot
Simple update from v1.5.9 to v1.5.13, which picks up some bugfixes, including a fix to a regression introduced in 1.5.9 (said fix landed in https://github.com/zenorocha/clipboard.js/releases/tag/v1.5.11)
Update:
> [clipboard] Patch-version update to v1.5.13

- material-ui/README.md
- material-ui/build.boot
- material-ui/resources/webpack.config.js
As @Deraen notified me about `material-ui-svg-icon` including React, I fixed it, but it decreased file size just slightly (roughly -100KB dev, -10KB minified).
Svg icons file is relatively big, simply because there's just many icons.  
Thanks a lot for a tip!
> [material-ui] Excluded react from material-ui-svg-icons

- moment/build.boot
- moment/resources/cljsjs/common/moment.ext.js
I did not see any big api changes, only one new method was added. I tested similar upgrade recently on my own projects, but I use small subset of moment, so can't say for sure if api changed.
> [moment.js] Upgrade 2.10.6 -> 2.15.2

- react/README.md
- react/build.boot
- react/resources/cljsjs/react/common/react.ext.js
Update:
React.DOM had the following missing externs: clipPath, dialog, picture,
summary, sup.
> [react] Add missing externs

- libtess/build.boot
This fix makes it work when compiling to `nodejs` target.
> Fix exports for libtess (node.js compat)

- codemirror/build.boot
- codemirror/resources/cljsjs/codemirror/common/codemirror.ext.js
Bumped codemirror version to 5.21.0 (changed d/l source because github distribution does no longer ship built version).
Added colorize extern by hand.
> Added colorize to codemirror externs, bumped to 5.21.0

- bootstrap-typeahead/README.md
Update:
I have received requests for better documentation / examples, this is the minimum viable example for this library.  Only the `README.md` is changed.
> [bootstrap-typeahead] Improved README.md example

- d3-tip/build.boot
d3 should not be a `:test` dependency for d3-tip.
> [d3-tip] Actually depend on d3

- aws-sdk-js/build.boot
Since @upgradingdave's [new blog post](http://www.upgradingdave.com/blog/posts/2017-01-08-cljsjs.html) mentions using awk-sdk-js's `build.boot` as the template, I figured out it's a good idea to make it a bit more exemplary.
> [aws-sdk-js] Clean up build.boot

- react-dates/build.boot
Update:
ReactDOM has been broken out from the core React library and needs to be loaded as a separate dependency.
> Added missing ReactDOM dependency

- react-flexbox-grid/README.md
> Add documentation about using react-flexbox-grid.

- semantic-ui-react/README.md
- semantic-ui-react/build.boot
- semantic-ui-react/resources/cljsjs/semantic-ui-react/common/semantic-ui-react.ext.js
Only one extern var is set `semanticUIReact` since all react elements can be safely retrieved via `aget` from that class.
New package:
> [semantic-ui-react] Initial commit v0.64.0

- material-ui-chip-input/build.boot
> [material-ui-chip-input] Update to version 0.12.0

- react-leaflet/README.md
- react-leaflet/build.boot
Update:
Update leaflet dependency to latest released version; Bump react-leaflet version.
> [react-leaflet] Update leaflet dependency to latest version

- react-mdl/build.boot
- react-mdl/resources/deps.cljs
I was getting an error when using the react-mdl package, `Cannot read property 'findDOMNode' of undefined`. I found it was due a missing dependency on `cljsjs.react.dom`, all this PR does is add that dependency.
> [react-mdl] Add cljsjs.react.dom dependency

- leaflet/README.md
- leaflet/build.boot
- leaflet/resources/cljsjs/common/leaflet.ext.js
Update:
**Leaflet**: I updated the extern by hand.
Leaflet package fails to compile with latest release of the ClojureScript compiler. The package build fails with the following strict warning:
`ERROR - Object literal contains illegal duplicate key "getBounds", disallowed in ES5 strict mode`.
This patch fixes 5 of these errors.
> [leaflet] Fix severe dupe key errors revealed by cljs compiler v1.9.456

- material-components/build.boot
> Update material components to 0.3.0

- aws-sdk-js/build.boot
- aws-sdk-js/resources/cljsjs/aws-sdk-js/common/aws-sdk-js.ext.js
The current AWS SDK build had 4 duplicate keys in the externs: `createBucket`, `getSignedUrl`, `upload` & `waitFor`. Duplicate keys aren't allowed in ES5 strict mode so as of clojurescript `1.9.456` this cljsjs package does **not** compile with `:optimizations "advanced"`.
See screenshot:
This PR removes removes the 4 duplicate keys.
> [aws-sdk-js]: fix duplicate keys in aws-sdk-js externs causing `:optimizations "advanced"` to fail on clojurescript 1.9.456

- babel-standalone/src/cljsjs/babel_standalone.clj
Renames the keys to enable tooling to dynamically resolve/require the lib.
> rename for dynamic require

- react-toolbox/README.md
> Point to the wrapper that makes it easy to use react-toolbox in Reagent.

- material-ui-chip-input/README.md
- material-ui-chip-input/build.boot
- material-ui-chip-input/resources/webpack.config.js
> [material-ui-chip-input] Update to version 0.12.2

- material-ui-chip-input/README.md
- material-ui-chip-input/build.boot
> [material-ui-chip-input] Update to version 0.13.0

- tether/README.md
- tether/build.boot
- tether/resources/cljsjs/tether/common/tether.ext.js
* Update Tether version to latest (1.4.0).
* Switch to handwritten externs because the automatically-generated
externs were missing a lot of methods and had some extra junk
* Add a small usage example to the README
* Tidy up `build.boot`, use latest `boot-cljsjs`
> [tether] Update to 1.4.0; add methods to externs

- reactstrap/build.boot
Fixed incorrect namespace for ReactDOM and exclude cljsjs/react from react-dom. See previous discussion https://github.com/cljsjs/packages/pull/1016.
> Add react chartjs 2

- material-components/build.boot
> Update material design components to 0.6.0

- semantic-ui-react/build.boot
- semantic-ui-react/resources/cljsjs/semantic-ui-react/common/semantic-ui-react.ext.js
Unfortunately I don't have the time to write the externs for this library by hand right now and I also use `goog.object/get` as the original author did. I did clean up the externs to remove the unnecessary `TopLevel` var and update the lib to the latest version.
Update:
> Update semantic-ui-react to 0.67.1

- material-components/README.md
- material-components/build.boot
Update:
This is an update to material-components to include the SCSS files from the source so that they can be used in theming the resulting css.  I then include the documentation on how to do that in the README.md.  This should have no breaking changes on current usage and increases the size of the jar by only about 60KiB.
> [material-components] Include SCSS into jar and document usage

- react-toolbox/build.boot
- react-toolbox/resources/webpack.config.js
Also migrate the webpack config to webpack2, but most important:
Fix an issue, where the currently released beta.6 includes its own
react.
This resolves `owner == null` issues with certain widgets, as well as
reduces the .inc.js size drastically.
Update:
> react-toolbox: 2.0.0-beta.6 -> 2.0.0-beta.7

- plotly/README.md
- plotly/build.boot
> updating plotly version to 1.25.0

- tableauwdc/README.md
- tableauwdc/build.boot
- tableauwdc/resources/cljsjs/common/tableauwdc.ext.js
Ran into https://github.com/cljsjs/boot-cljsjs/issues/48 which results
in broken JAR when built on Windows, but should work on a sane(r) platform.
New package:
> [tableauwdc] Initial commit

- fixed-data-table/build.boot
Some of the functionality in 0.6.3 depends on `ReactDOM`
being present:
https://github.com/facebook/fixed-data-table/blob/master/package.json
Update:
> [fixed-data-table] Bump React to 0.14.0

- react-relay/README.md
This PR makes the example in the react-relay README.md a bit more
bulletproof. The example didn't handle GraphQL fragments with newlines
in them, causing the Node process to fail.
> Add str/trim-newline to react-relay README.md

- opentype/build.boot
> Update opentype to 0.6.9

- react-relay/build.boot
Update:
Building package from Github, since the latest version is not available as a webjar.
> Update react-relay to 0.10.0

- firebase/build.boot
- firebase/resources/deps.cljs
This externs file is already included in the upstream externs, but it was
previously excluded from the CLJS externs declaration.  This adds it
so that OAuth logins will work in the browser.
> [firebase] Add existing externs to CLJS externs declaration

- react-autosuggest/build.boot
API changes don't impact existing externs https://github.com/moroshko/react-autosuggest/releases/tag/v9.0.0
> update react-autosuggest to v9.0.0

- libphonenumber/build.boot
Some of those files have the same goog.provide and define the same symbols (with different content) as the "main" files, creating errors due to the wrong version of some symbols being loaded.
An example of these duplicate symbols is `i18n.phonenumbers.metadata.countryCodeToRegionCodeMap` defined both in [metadata.js](https://github.com/googlei18n/libphonenumber/blob/57cb83dc236c6103057d54591cdbcc8a8309226e/javascript/i18n/phonenumbers/metadata.js#L33-L248) and [metadatafortesting.js](https://github.com/googlei18n/libphonenumber/blob/57cb83dc236c6103057d54591cdbcc8a8309226e/javascript/i18n/phonenumbers/metadatafortesting.js#L33-L61)
This example of metadatafortesting.js defines a country to metadata
mapping for a reduced set of countries. When this mapping ends being
loaded instead of the …
> Remove test and demo files from libphonenumber

- react-sticky/build.boot
Modified build.boot to ensure that cljs-deps reflects a dependency on cljsjs.react.dom.
Update:
Extern: The API did not change.
> [react-sticky] Fix dependency for react-dom

- material-ui-chip-input/README.md
- material-ui-chip-input/build.boot
> [material-ui-chip-input] Update to version 0.13.5

- vega-embed/build.boot
vega-embed 3.0.0-beta.14
Update:
> vega-embed 3.0.0-beta.14

- auth0-lock/README.md
- auth0-lock/build.boot
Update:
Updated version to latest 10.16.0
> Update auth0-lock to 10.16.0

- jspdf/README.md
None of the pre-suggested lines seemed relevant. All I did was change the md file.
> Fix typo in jspdf readme file

- qs/README.md
- qs/build.boot
- qs/buildjs/build.js
- qs/buildjs/package.json
- qs/buildjs/qs.js
- qs/resources/cljsjs/qs/common/qs.ext.js
Packaged https://github.com/ljharb/qs library. Browserify integration was taken from iconv package.
New package:
> Package qs library

- pdfjs/README.md
- pdfjs/build.boot
> PDFJS upgrade to 1.8.188

- material-components/build.boot
> Update material components to 0.12.1

- quill/build.boot
* Updated the quill version to 1.2.5
* `quill.core.js` is a minimal version intended for use [with webpack](https://quilljs.com/guides/adding-quill-to-your-build-pipeline/) for a customized build. The target filename `quill.core.inc.js` was coming before `quill.inc.js` when sorted, and during dev only the minimal version was being loaded without themes / modules.
Update:
> [quill] bump version, remove quill.core.js

- react-number-format/README.md
- react-number-format/build.boot
- react-number-format/resources/cljsjs/react-number-format/common/react-number-format.ext.js
New package: react-number-format
Update:
> Adding a currency formatting component

- material-components/build.boot
This is a fix for https://github.com/cljsjs/packages/pull/1208.  It's the same, but successfully fixes #1203.  I tested it on the new circleci Docker image.
Update:
Extern: The API did not change.
I have updated to 0.13.0, as that was released recently, and I also changed sh to dosh.
dosh allows circleci to fail if the build doesn't work. It built fine on node 8.1.0 on my local MacMini.
It seems that there was an issue with postinstall not being run, so I run it automatically now.
> Update material components 0.13.0 build fix

- highlight/README.md
- highlight/build.boot
Update:
Upgraded highlight.js to 9.12.0 which contains bug fixes and support for additional languages.
> [highlight] Update highlight.js to 9.12.0

- filestack/README.md
- filestack/build.boot
- filestack/resources/cljsjs/filestack/common/filestack.ext.js
Update version to 0.6.3 which is the latest for Filestack V3.
**Breaking changes**
Reference for new version can be found here https://github.com/filestack/filestack-js
Migration guide: https://www.filestack.com/docs/javascript-api/migrating-to-v3
**Extern:** I updated the extern with generator. (https://jmmk.github.io/javascript-externs-generator/)
> Update filestack to V3

- react-datetime/README.md
- react-datetime/build.boot
- Adds `react-dom` as a new dependency as it has been split out from `react` since the last update
- Cleaned up some unneeded requires in `boot.build`
Update:
> [react-datetime] Update to 2.8.10

- material-ui-chip-input/README.md
- material-ui-chip-input/build.boot
> [material-ui-chip-input] Update to version 0.15.0

- fixed-data-table-2/README.md
- fixed-data-table-2/build.boot
This library tries to use "findDOMNode" from cljsjs.react.dom, but hasn't declared a dependency on it. This results in runtime errors if cljsjs.react.dom has not been loaded before (which is probably why this has gone unnoticed so far).
> Add cljsjs.react.dom as a dependency for fixed-data-table-2

- mathbox/README.md
Just fixed a typo [txt](link_id) -> [txt][link_id].
> Fix links in mathbox/readme

- material-colors/README.md
- material-colors/build.boot
- material-colors/resources/cljsjs/material-colors/common/material-colors.ext.js
New package:
Note: This library is required by react-color, for which a package will be submitted once this is accepted.
> [material-colors] New package - version 1.2.5

- create-react-class/build.boot
- create-react-class/resources/deps.cljs
- react/build.boot
- react/resources/cljsjs/react/common/react.js
- react/resources/react-deps.cljs
- react/resources/react-dom-deps.cljs
- react/resources/react-dom-server-deps.cljs
New Cljs supports `:global-exports` option on foreign-libs which will allow using normal `:require` to access JS objects from foreign libs:
```
;; foreign-lib
:global-exports {react-dom ReactDOM}
;; cljs
(ns ... (:require [react-dom :as react-dom]))
(react-dom/render ...)
;; => window.ReactDOM.render(...)
;; or something similar
```
This change keeps the existing `cljsjs.react` & co namespaces but adds new, which use the same names as Node packages, for easy transition:
- cljsjs.react -> react
- cljsjs.react.dom -> react-dom
- cljsjs.react.dom.server -> react-dom/server
- cljsjs.create-react-class -> create-react-class
> React :global-exports support

- antd/README.md
Update: Minor fix to resource path typo in antd's README.md.
**Extern:** No changes
> [antd] Fix resource name typo.

- raven/build.boot
Update:
The extern doesn't change from version 3.16.1. This is just meant to get the latest version.
> Update Raven to 3.17.0

- recharts/build.boot
- recharts/resources/cljsjs/recharts/common/recharts.ext.js
This comes up as warnings in the build.  I assume it should be Recharts.  Bad copy-pasta?
Update:
> Missing R in Recharts

- plotly/build.boot
> Upgrade Plotly to v1.30.0-0

- material-components/build.boot
Update:
Bump version to 0.17.0.  Builds fine on macos.
> [material-components] update version 0.17.0

- material-ui-chip-input/README.md
- material-ui-chip-input/build.boot
> [material-ui-chip-input] Update to version 0.17.0

- optiscroll/build.boot
* Use minified JavaScript file provided by Optiscroll author because
generated was empty
> [optiscroll] Fix broken build with `:advanced` optimizations

- semantic-ui-react/README.md
- semantic-ui-react/build.boot
> [semantic-ui-react] Bump to 0.72.0

- material-components/build.boot
> [material-components] Update to 0.19.0-0

- material-ui-chip-input/build.boot
> [material-ui-chip-input] Update to version 0.17.2

- react-autosuggest/README.md
- react-autosuggest/build.boot
- react-autosuggest/resources/cljsjs/react-autosuggest/common/react-autosuggest.ext.js
Commit and PR based on https://github.com/cljsjs/packages/pull/1085.
Minimal api change, https://github.com/moroshko/react-autosuggest/releases/tag/v9.3.2
> React-autosuggest updated  to v9.3.2

- enzyme/README.md
- enzyme/build.boot
- enzyme/resources/build/helper.js
- enzyme/resources/build/webpack.config.js
- enzyme/resources/cljsjs/enzyme/common/enzyme.ext.js
- enzyme/resources/deps.cljs
This is my very first attempt to create a cljsjs package (please criticize - so I can learn). I desperately need to make it possible to use Enzyme in browser environment.
I need help with improving this package:
a) it currently only works with React 15
b) I was trying to find a way to use Global exports feature https://clojurescript.org/news/2017-07-30-global-exports ,so it could be required like this:
(require '[cljsjs.enzyme :as enzyme])
but couldn't figure it out
> Adds airbnb/enzyme

- react-virtualized/README.md
- react-virtualized/build.boot
> upgrade react-virtualied to version 9.10.1

- react-flip-move/build.boot
update to react-flip-move 2.9.17
- switched to using unpkg
Update: 
> update to react-flip-move 2.9.17

- firebase/resources/deps.cljs
The externs are taken from Firebase's externs in its repo.
Messaging specifically was missing, which is a main feature.
**Extern:** Included in Firebase distribution.
> Added missing Firebase externs

- pixi/README.md
- pixi/build.boot
> PixiJS v4.6.1

- semantic-ui/build.boot
Update:
**Extern:** Not needed - was not there.
> Bump semantic-ui to 2.2.13

- pixi/README.md
- pixi/build.boot
> PixiJS v4.6.2

- slate-react/README.md
- slate-react/build.boot
- slate-react/resources/cljsjs/common/slate-react.ext.js
New package. Should probably not be merged until https://github.com/cljsjs/packages/pull/1428 is approved/merged since it has an explicit dependency on it.
New package:
> Add slate-react

- slate-html-serializer/README.md
- slate-html-serializer/build.boot
- slate-html-serializer/resources/cljsjs/common/slate-html-serializer.ext.js
Adds html serializer lib for Slate
New package:
> add slate-html-serializer

- auth0-lock/README.md
- auth0-lock/boot-cljsjs-checksums.edn
- auth0-lock/build.boot
> auth0-lock: update to 10.24.1

- accounting/README.md
- accounting/build.boot
- accounting/resources/cljsjs/accounting/common/accounting.ext.js
The existing externs for accounting would generate several warnings similar to the following when building a project with advanced optimizations enabled. This PR updates the externs to fix this issue.
```
WARNING - name accounting is not defined in the externs.
accounting.toFixed = function(value, precision) {}
^^^^^^^^^^
```
> [accounting] Update externs

- react-router-dom/README.md
- react-router-dom/build.boot
- react-router-dom/resources/cljsjs/react-router-dom/common/react-router-dom.ext.js
This PR adds `react-router-dom`. This is not to be confused with the `react-router` package which is an old version and published to `npm` under a different name.
> Added react-router-dom@4.2.2

- auth0/README.md
- auth0/boot-cljsjs-checksums.edn
- auth0/build.boot
- auth0/resources/cljsjs/auth0/common/auth0.ext.js
Bumping Auth0 to 9.2.1 (instead of 9.2.2) because Auth0 Lock 11.2.2 depends on this specific version.
Externs auto-generated.
> Auth0 bump to 9.2.1

- quill/boot-cljsjs-checksums.edn
- quill/build.boot
- quill/resources/cljsjs/quill/common/quill.ext.js
* Added `boot-cljsjs-checksums.edn` for quill
* Updated quill to 1.3.5
* Updated the description according to the official documentation
* Updated the API
> Updated quill to 1.3.5; added checksums

- iota-mam/README.md
- iota-mam/build.boot
Adds [IOTA ledger's mam.client.js](https://github.com/iotaledger/mam.client.js). There is no official release of mam.client.js, so it uses the master.zip. Is this okay for now?
> [iota-mam] Add iotaledger/mam.client.js

- iota-mam/README.md
Description of a necessary step for the require to work.
I don't know how to properly compile the wasm into the JavaScript file. The [`mam.node.js`](https://raw.githubusercontent.com/iotaledger/mam.client.js/master/lib/mam.node.js) file doesn't succeed in proving a `js/Mam` object.
> [iota-mam] Add installation instructions

- react-transition-group/build.boot
This package was switching the minified and unminified source, with hilarious results
See #1501
> [react-transition-group] download minified source to correct target

- react-highlight/build.boot
- react-highlight/resources/webpack.config.js
This isn't complete or ready to be merged. I've opened https://github.com/bvaughn/react-highlight.js/issues/11 to ask the original author to tag a new release, I've just forked the library and tagged it myself for testing.
I'm also not sure whether I've properly added PropTypes, I still get warnings in the console about them being used. This is my first CLJSJS package, does what I've done look correct?
> Update react-highlight to 1.0.7

- slate-react/README.md
- slate-react/build.boot
- slate-react/resources/cljsjs/common/slate-react.ext.js
Upgraded library.
Will fail build until https://github.com/cljsjs/packages/pull/1542 is merged.
> [slate-react] Upgrade slate-react to 0.12.4-0

- slate-html-serializer/README.md
- slate-html-serializer/build.boot
- slate-html-serializer/resources/cljsjs/common/slate-html-serializer.ext.js
This PR will fail until https://github.com/cljsjs/packages/pull/1542 is merged.
> [slate-html-serializer] Update slate-html-serializer to 0.6.1-0

- react-sortable-hoc/README.md
- react-sortable-hoc/boot-cljsjs-checksums.edn
- react-sortable-hoc/build.boot
- react-sortable-hoc/resources/cljsjs/react-sortable-hoc/common/react-sortable-hoc.ext.js
Adds the React Sortable (HOC) cljsjs package
> [react-sortable-hoc] Add cljsjs/react-sortable-hoc "0.5.0-0"

- react-highlight/build.boot
The previous commit in #1512 doesn't run properly, there is something about the new packaging method I used there that doesn't work correctly. I'd like to update to the new method, but in the meantime, here is a version for 1.0.7 which does work correctly, and uses the previous packaging method.
> Revert to previous format for building react-highlight package

- react-color/README.md
- react-color/boot-cljsjs-checksums.edn
- react-color/build.boot
- react-color/resources/cljsjs/react-color/common/react-color.ext.js
Requires PR #1554 
Updated react-color to 2.13.8. Updated to the latest boot-cljsjs, and added checksums & deps.
Note: Latest is 2.14.0, but there is no release zip, an issue has been added and I will follow up with an update when that is rectified.
> [react-color] Upgrade react-color to 2.13.8, Moved to new boot-cljsjs

- material-components/boot-cljsjs-checksums.edn
- material-components/build.boot
I believe there are large changes that happened in this version upgrade, including seeming to obviate the need for some of the externs data.
It also adds the checksum data, so this should be more secure than previously.
It works locally for what I've used older versions for.
> [material-components] Update to 0.34.1

- react-autosize-textarea/README.md
- react-autosize-textarea/build.boot
Fixes improperly named cljsjs.react.dom require and bumps to latest increment of current react libraries.
> [react-autosize-textarea] Fix cljsjs.react.dom require

- react-datepicker/README.md
- react-datepicker/build.boot
Fixes improperly named cljsjs.react.dom require and bumps to latest increment of current react libraries.
> [react-datepicker] Fixes improper cljsjs.react.dom require

- react-datepicker/README.md
- react-datepicker/build.boot
Pulls in fixed react-onclickoutside with proper react-dom require.
Will not build properly until https://github.com/cljsjs/packages/pull/1567, https://github.com/cljsjs/packages/pull/1569, https://github.com/cljsjs/packages/pull/1570, and https://github.com/cljsjs/packages/pull/1571 are merged.
> [react-datepicker] Pull in fixed react-onclickoutside and other needed deps

- recharts/README.md
- recharts/boot-cljsjs-checksums.edn
- recharts/build.boot
Including latest recharts dependency `1.0.0-beta.10-2` caused my application to fail until I made the following changes:
* bumped to latest react/react-dom dependencies
* Cleaned up build.boot
* Required 'react-dom' which is known peer dependency
* Used `validate` instead of `validate-checksums`.
> [recharts] Patch upgrade and cleanup

- react-sticky/boot-cljsjs-checksums.edn
- react-sticky/build.boot
- react-sticky/resources/webpack.config.js
Update React Sticky to latest version as there have been a number of small bug fixes since version 6.0.1.
Update checksum validation
Add checksum file
Update cljsjs dependencies
Fix minor indentation issue in webpack.config.js
> [react-sticky] Update to version 6.0.2

- react-popper/README.md
- react-popper/build.boot
Get the new version of PopperJS that isn't broken.
Requires https://github.com/cljsjs/packages/pull/1582 to build properly.
> [react-popper] Patch upgrade to fix dep

- react-datepicker/README.md
- react-datepicker/boot-cljsjs-checksums.edn
- react-datepicker/build.boot
* Upgraded to latest react-datepicker
* Fix Readme instructions
* Get fixed react-popper (with fixed popperjs)
Requires https://github.com/cljsjs/packages/pull/1583 to build properly
> [react-datepicker] Upgrade to 1.4.1

- semantic-ui-react/README.md
- semantic-ui-react/boot-cljsjs-checksums.edn
- semantic-ui-react/build.boot
changed version semantic-ui to 0.79.1
https://github.com/Semantic-Org/Semantic-UI-React/compare/v0.78.2...v0.79.1
change version of react (and react.dom) to 16.xx like it describe in package.json 
https://github.com/Semantic-Org/Semantic-UI-React/blob/v0.79.1/package.json#L122
changed tested with 0.79.0 version and after for 0.79.1 latest tag
> Update semantic-ui-react 0.79.1

- react-motion/README.md
- react-motion/boot-cljsjs-checksums.edn
- react-motion/build.boot
Bump react-motion to the latest version, and add support for :global-exports.
Tried locally with `boot package install target`, also tried out the :global-exports support.
> react-motion 0.5.2 + :global-exports

- react-ultimate-pagination/README.md
- react-ultimate-pagination/boot-cljsjs-checksums.edn
- react-ultimate-pagination/build.boot
- react-ultimate-pagination/resources/webpack.config.js
Also add support for :global-exports
Closes #1156
> Bump react-ultimate-pagination to v1.2.0

- semantic-ui-react/boot-cljsjs-checksums.edn
- semantic-ui-react/build.boot
Bumped semantic-ui-react to 0.80.0. Left the existing "empty" externs file as
is, updated checksums.
> [semantic-ui-react] Bump to 0.80.0

- google-analytics/build.boot
Adds the Apache v2 license, which is the license of the google-analytics library
> Add license to cljsjs/google-analytics

- libphonenumber/build.boot
- libphonenumber/resources/deps.cljs
The trailing slash in deps.cljs -> :libs causes an exception [1] to be thrown when this library is used in conjunction with figwheel 0.5.16 (latest at PR time).
Updating from `:checksum` to `validate` call produced an empty `boot-cljsjs-checksums.edn`
[1]
```
Failed to compile build :dev from ["src/cljs" "src/cljc" "checkouts/nsfw/src/cljs" "checkouts/nsfw/src/cljc"] in 27.072 seconds.
----  Exception    ----
/cljs/18n/phonemetadata.pb.js is not a relative path
----  Exception Stack Trace  ----
java.lang.IllegalArgumentException: /cljs/18n/phonemetadata.pb.js is not a relative path
at clojure.java.io$as_relative_path.invokeStatic (io.clj:414)
clojure.java.io$file.invokeStatic (io.clj:426)
clojure.java.io$file.invoke (io.clj:418)
cljs.closure$write_javascript.invokeStatic …
```
> [libphonenumber] Fix 'is not a relative path' exception cljsjs.libphonenumber "8.4.1-2"

- slate-html-serializer/README.md
- slate-html-serializer/boot-cljsjs-checksums.edn
- slate-html-serializer/build.boot
Also some cleanup and validation.
Will fail build until https://github.com/cljsjs/packages/pull/1633 is merged.
> [slate-html-serializer] Upgrade to 0.6.3

- slate-react/README.md
- slate-react/boot-cljsjs-checksums.edn
- slate-react/build.boot
Also did some cleanup and added validation.
Build will fail until https://github.com/cljsjs/packages/pull/1633 is merged.
> [slate-react] Upgrade to 0.12.6

- react/README.md
- react/boot-cljsjs-checksums.edn
- react/build.boot
I did not update the externs as it appears they are generated differently than other packages and the ones automatically generated using React via unpkg are unlike the ones we have currently (they are much shorter).
@Deraen Let me know what is needed to upgrade externs (if it's anything special) and I can update this PR.
I did notice it looks like we have 'React 15' externs at the top then additions for 'React 16.3' on the bottom. I'm unaware if that is an intentional separation.
> [react] Upgrade react to 16.4.0

- draft-convert/README.md
- draft-convert/build.boot
- draft-convert/resources/cljsjs/draft-convert/common/draft-convert.ext.js
Add the draft-convert library v2.1.2 for use with draft-js.
> draft-convert initial commit v2.1.2

- vega/README.md
- vega/build.boot
- vega/resources/cljsjs/common/vega.ext.js
Update vega to 3.3.1 - last release before new 4.X dev
Because of dependencies, this must be merged before the new commits and PRs for vega-lite, vega-embed and vega-tooltip
> [vega] Update to 3.3.1 - last before 4.x dev

- vega-lite/README.md
- vega-lite/build.boot
- vega-lite/resources/cljsjs/common/vega-lite.ext.js
Update vega-lite to 2.6.0 - last release before new 3.X dev
Because of dependencies, this must be merged before the new commits and PRs for vega-embed and vega-tooltip
> [vega-lite] Update to 2.6.0 - last before 3.x dev

- react-number-format/boot-cljsjs-checksums.edn
- react-number-format/build.boot
I don't think the version number needs to be bumped. Just putting this in so that it's there for the next time the library version is bumped.
> [react-number-format] Add checksums

- textures/README.md
- textures/boot-cljsjs-checksums.edn
- textures/build.boot
Added dependency on d3 to remove requirement for external include and better integration with advanced compile. Lock version of the source js file to ensure build reproducibility.
> [textures] Add d3 dependency and lock version of js file source.

- react-sortable-hoc/boot-cljsjs-checksums.edn
- react-sortable-hoc/build.boot
- react-sortable-hoc/resources/cljsjs/react-sortable-hoc/common/react-sortable-hoc.ext.js
* Update to latest version as of 8/10/2018. 
* Generated & added missing extern definitions (based off of jmmk/javascript-externs-generator result)
> [react-sortable-hoc] Update to version 0.8.2 & Update extern definitions to align with new version

- react-test-renderer-shallow/README.md
- react-test-renderer-shallow/boot-cljsjs-checksums.edn
- react-test-renderer-shallow/build.boot
- react-test-renderer-shallow/resources/cljsjs/react-test-renderer-shallow/common/react-test-renderer-shallow.ext.js
SSIA: Another package spun out of React; needed this for Reacl.
> Initial import of react-test-renderer-shallow.

- iota-mam/build.boot
It conflicted with iota.js:
when building a project that uses both iota and iota-mam with advanced compilation the extern files conflicted. The reason was that iota-mam had an externs file `iota/iota.ext.js` and that is the same as the one for iota. This commit changes the iota-mam externs file to `iota-mam/iota-mam.ext.js`.
> [iota-mam] fix externs name

- codemirror/build.boot
- codemirror/resources/cljsjs/codemirror/common/codemirror.ext.js
After reading the guidelines a couple of times I think this PR is fine. I apologize in advanced if it is not. It would seem that this package is not using the latest `boot-cljsjs` since no checksum file was produced by `boot package install`.
I've tested the changes and when using advanced compilation, `toTextArea` can be used without problem.
> [codemirror] Add toTextArea to extern

- vega/README.md
- vega/boot-cljsjs-checksums.edn
- vega/build.boot
- vega/resources/cljsjs/vega/common/vega.ext.js
Update to Vega 4.4.0 in order to update vega-* packages to their latest
> [vega] update to latest release

- elkjs/README.md
- elkjs/boot-cljsjs-checksums.edn
- elkjs/build.boot
- elkjs/resources/cljsjs/elkjs/common/elkjs.ext.js
Adding elkjs, the successor for klayjs, which already exists in this repo.
> [elkjs] Add elkjs - eclipse layout kernel

- mathjax/README.md
- mathjax/build.boot
Initial package for mathjax. Uses current released version 2.7.5
> [mathjax] initial package - version 2.7.5

- phaser/boot-cljsjs-checksums.edn
- phaser/build.boot
* Updates the cdn uri as the scheme doesnt work for the latest release.
* Updates phaser to latest release 3.16.2
* Adds checksums edn file.
* Adds validates-checksum to build.boot
* Removes `map` file from deftask as latest phaser does not ship with a map file.
> [Phaser] Updates phaser to 3.16.2 release.

- paperjs/boot-cljsjs-checksums.edn
- paperjs/build.boot
* Updates paperjs to 0.12.0 release.
* Adds checksum edn file.
* Updates build.boot to validate checksums and remove earlier inline checksum.
> [paperjs] Updates paperjs to 0.12.0

- react/boot-cljsjs-checksums.edn
- react/build.boot
* Fix a bug that caused inputs to behave incorrectly in UMD builds. ([@gaearon](https://github.com/gaearon) in [#14914](https://github.com/facebook/react/pull/14914))
* Fix a bug that caused render phase updates to be discarded. ([@gaearon](https://github.com/gaearon) in [#14852](https://github.com/facebook/react/pull/14852))
* Unwind the context stack when a stream is destroyed without completing, to prevent incorrect values during a subsequent render. ([@overlookmotel](https://github.com/overlookmotel) in [#14706](https://github.com/facebook/react/pull/14706/))
> Update react to 16.8.3

- react-quill/build.boot
I've updated the version of `react-quill` from `1.0.0-beta-5` to `1.1.0`. I also bumped the versions of the `quill` and `react` deps to match.
> [react-quill] Update to 1.1.0

- libphonenumber/build.boot
I couldn't figure out how to get the boot scripts to create a proper checksum file for this package, but I manually downloaded the archive and created an updated MD5 for it.
I tested the resulting build in my downstream app and it appears to be OK.
> [libphonenumber] Update to 8.10.8

- vega-embed/build.boot
- vega-lite/build.boot
- vega-tooltip/build.boot
- vega/boot-cljsjs-checksums.edn
- vega/build.boot
built against vega 5.3.2-0 and vega-lite 3.0.0-0
> [vega-embed, vega-tooltip] -> versions 4.0.0-0, 0.17.0-0 respectively

- highcharts/boot-cljsjs-checksums.edn
- highcharts/build.boot
- highcharts/resources/cljsjs/highcharts/common/highcharts.ext.js
Add option treemap.events.setRootNode
Add jitter feature to scatter plots
Add feature to set legend.width
Add overlap stacking to waterfall charts
https://www.highcharts.com/blog/changelog/
> [highcharts] Upgrade to latest version (7.0.3)

- oidc-client/README.md
- oidc-client/build.boot
- oidc-client/resources/cljsjs/oidc-client/common/oidc-client.ext.js
This PR adds externs for the User object, which is [described in the documentation](https://github.com/IdentityModel/oidc-client-js/wiki#user) (and can thus be considered a public API) but was not yet covered by the externs file.
> [oidc-client] More externs: User object

- material-ui-pickers/boot-cljsjs-checksums.edn
- material-ui/README.md
- material-ui/boot-cljsjs-checksums.edn
- material-ui/build.boot
- material-ui/resources/package.json
(Don't know why material-ui-pickers will be build too)
> [material-ui] Updated to 4.3.0 + [material-ui-pickers] Fix Checksums

- ag-grid-community/build.boot
This allows users to create custom builds of the ag-grid styles by using
sass4clj without copy & pasting the styles (and potentially having
them to fall out of sync).
> [ag-grid-community] Include scss files

- material-ui/README.md
- material-ui/boot-cljsjs-checksums.edn
- material-ui/build.boot
- material-ui/resources/package.json
> [material-ui] Updated to 4.3.1

- simplebar/README.md
- simplebar/boot-cljsjs-checksums.edn
- simplebar/build.boot
- simplebar/resources/cljsjs/simplebar/common/simplebar.ext.js
This is the first packaging of simplebar, which provides
the ability to include custom scrollbars on elements.
Cross-browser support. Tested Locally.
> [simplebar] Initial SimpleBar CLJSJS Package

- react/resources/cljsjs/react/common/react.ext.js
The new lifecycle method componentDidCatch() in React 16 receives two paramaters:
1. error
1. info
Add them to react.ext.js to match this condition.
Tested Locally.
References:
https://reactjs.org/docs/react-component.html#componentdidcatch
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react/index.d.ts#L587
> [React] Add parameters to componentDidCatch

- react-stripe-elements/build.boot
- react-stripe-elements/resources/cljsjs/react-stripe-elements/common/react-stripe-elements.ext.js
Stripe Elements injects some props dynamically in a way that externs generation can't detect. We added them manually to the main externs file. Is there a better way to do this instead?
> [react-stripe-elements] Add injected props in StripeProvider

- material-ui/README.md
- material-ui/boot-cljsjs-checksums.edn
- material-ui/build.boot
- material-ui/resources/package.json
> [material-ui] Updated to 4.8.3

- sentry-browser/README.md
- sentry-browser/boot-cljsjs-checksums.edn
- sentry-browser/build.boot
- sentry-browser/resources/cljsjs/sentry-browser/common/sentry-browser.ext.js
Upgrade sentry-browser package to 5.11.1 (latest) version.
Externs created with clijs tool.
> [sentry-browser] Upgrade lib version and checksums.

- react-test-renderer/boot-cljsjs-checksums.edn
- react-test-renderer/build.boot
Updated react-test-renderer package to same version as cljsjs/react.
> [react-test-renderer] Updated to 16.13.0

- react-test-renderer-shallow/boot-cljsjs-checksums.edn
- react-test-renderer-shallow/build.boot
Updated react-test-renderer-shallow to same version as cljsjs/react.
> [react-test-renderer-shallow] Updated to 16.13.0

- material-ui-currency-textfield/README.md
- material-ui-currency-textfield/boot-cljsjs-checksums.edn
- material-ui-currency-textfield/build.boot
- material-ui-currency-textfield/resources/cljsjs/material-ui-currency-textfield/common/material-ui-currency-textfield.ext.js
- material-ui-currency-textfield/resources/main.js
- material-ui-currency-textfield/resources/package.json
- material-ui-currency-textfield/resources/webpack.config.js
Hi there! I've prepared a package for this library:
https://github.com/unicef/material-ui-currency-textfield
It passes the build locally, also works inside the cljs app. Can you please review the PR and merge it if it's ok?
Also one question from me - is it mandatory to package separately [autonumeric](https://github.com/unicef/material-ui-currency-textfield/blob/master/package.json#L78) direct dependency of this library? Currently it is bundled with webpack directly into dev/prod bundles.
> [material-ui-currency-textfield] Add version 0.8.6

- snabbdom/README.md
- snabbdom/build.boot
- snabbdom/resources/deps.cljs
Noticed this while testing with shadow-cljs. Tested the corrected version after `boot package install target` locally with shadow-cljs and works.
> [snabbdom] fix deps.cljs bad paths

- google-diff-match-patch/build.boot
This project seems to have been moved to github:
https://github.com/google/diff-match-patch
It doesn't seem to use any version numbers (or releases), so I've used the git hash as the version (not sure if this is okay). Please let me know if further changes are needed. Thanks!
> Update google-diff-match-patch, use new upstream

- react-virtualized/README.md
- react-virtualized/boot-cljsjs-checksums.edn
- react-virtualized/build.boot
- react-virtualized/resources/cljsjs/react-virtualized/common/react-virtualized.ext.js
Updated react-virtualized 9.21.2 externs manually since the automatic script left out at least these 2 functions:
```
ReactVirtualizer.CellMeasurerCache.clear
ReactVirtualizer.CellMeasurerCache.clearAll
```
> React-virtualized 9.21.2-1

- highcharts/README.md
- highcharts/build.boot
Highcharts was generating `deps.cljs` with the `:file` pointing to the
minified file and `:file-min` pointing to the non-minified file. This
commit reverts it to how it should be.
> [highcharts] Fix highchart deps.cljs file and file-min options

- quaternion/README.md
- quaternion/boot-cljsjs-checksums.edn
- quaternion/build.boot
- quaternion/resources/package.json
This PR adds support for the https://github.com/infusion/Quaternion.js library, for working with quaternions.
> [quaternion] Add support for the quaternion package

- bigfraction/README.md
- bigfraction/boot-cljsjs-checksums.edn
- bigfraction/build.boot
- bigfraction/resources/package.json
This PR adds support for the bigfraction.js version of the https://github.com/infusion/Fraction.js library, for working with rational numbers.
> [bigfraction] Add support for the bigfraction.js code inside the Fraction.js package

- bigfraction/README.md
- bigfraction/boot-cljsjs-checksums.edn
- bigfraction/build.boot
- bigfraction/resources/package.json
This PR upgrades the bigfraction package to version 4.1.1.
NOTE: Please merge this after #2190 , so that we can get that bugfix published for the older version. Thank you!
> Upgrade bigfraction to 4.1.1

- react-share/build.boot
update project group of react-share according to 1b387147c258730b7c02544ed341f80adb4ed914
> [react-share] change react-share project group to io.github.cljsjs

- konami/README.md
- konami/boot-cljsjs-checksums.edn
- konami/build.boot
Hi,
This PR updates the upstream library - konami-js- version to 1.6.3 since the author made a release a couple of days ago.
I also took the opportunity to update the README a bit.
Looking at the lib changes there are no API changes, mostly cosmetic (which can be seen from the unchanged minified file checksum).
Cheers.
> [konami] Update upstream library version to 1.6.3

- js-joda/boot-cljsjs-checksums.edn
- js-joda/build.boot
- js-joda/resources/cljsjs/js-joda/common/js-joda.ext.js
Adds the ToNativeJSConverter class with its two functions: toDate and toEpochMilli.
Also adds boot checksum to the library.
> [js-joda] Add missing externs for ToNativeJSConverter

- esri-leaflet/README.md
- esri-leaflet/build.boot
- esri-leaflet/resources/cljsjs/esri-leaflet/common/esri-leaflet.ext.js
The 'var L' syntax was shadowing/overriding externs declared by other Leaflet libraries. The new syntax just declares 'L.esri' without affecting other 'L.XXX' externs.
> [esri-leaflet] Fix library externs shadowing other L externs
